### ISSUE TITLE
Seems to be buggy lately.

### ISSUE THREAD

**Issue by trusktr** [airblade/vim-gitgutter#492] opened 2018-02-26 06:01 UTC
> What is the latest commit SHA in your installed vim-gitgutter? 

b27ee4d602d7ce6f7b7caf8e9ecb8eded57ffe0a

> What vim/nvim version are you on?

NeoVim 0.2.2

---

vim-gitgutter seems to be buggy in macOS lately. I looked through the commit history, and I see there's been lots of activity lately. Maybe it's related?

What I'm experiencing is that the gutter will show a bunch of `+` even for lines that weren't added, that have already existed. Also, alt-tabbing out of and then back to NeoVim is causing it to update ("realtime"), and sometimes it updates to erroneous state (f.e. the invalid `+` markers) and sometimes valid state.

This hasn't happened before, until I got this MacBook Pro just within the last month, and installed fresh versions of all my plugins.

Not idea what may be causing it. It's just completely flaky right now. I have other plugins enabled, but I haven't tried toggling them on/off to see if the problem goes away, I don't have enough time at the moment.

Maybe what I can do, next time it happens, is quit, disable all plugins except for fugitive, and reopen the same file, and see if it keeps happening.

**Comment by trusktr** [comment] 2018-02-26 06:10
Wish I knew how to reproduce, but it seems to happen randomly. Probably have to bisect to find the commit, but no time at the moment.

**Comment by airblade** [comment] 2018-02-26 08:53
There was a big update in 5bfe5b9 and various bugfixes since then.

It's working for me and passing all the tests, but evidently there's something awry – I wish I could help but without more information there's not much I can do.

Looking forward to hearing more when you have time.

**Comment by relapi** [comment] 2018-02-26 20:32
I'm seeing the same issue, randomly as well.

**Comment by dkarter** [comment] 2018-02-26 22:21
Same here

Here's a video - hope it helps with replication. I could not show the code so it is blurred but it should give enough information to see that git gutter is not working properly.

 https://www.dropbox.com/s/l1f61447iganh63/gitgutter%20bug.mp4?dl=0

I'm on the latest NeoVim.

**Comment by airblade** [comment] 2018-02-27 11:30
Thanks for the video.  It looks like the plugin's not working properly, as far as I can tell, but it doesn't help with replication unfortunately.

**Comment by brolycjw** [comment] 2018-02-28 09:12
Had the same issue, easiest workaround right now is to specify the commit right before the big refactor with vimplug or whatever plugin manager you are using.

**Comment by airblade** [comment] 2018-02-28 11:44
Have any of you managed to come up with repro steps?

Is anyone experiencing this problem with vim, or are you all using neovim?

**Comment by rubyconn** [comment] 2018-02-28 12:11
I recently made the switch to neovim, and I'm pretty sure that's when these issues started popping up. I experience them daily, so I'll see if I can find a surefire way to reproduce them.

**Comment by brolycjw** [comment] 2018-03-01 00:55
Yes, I am using neovim too.

**Comment by TyPott** [comment] 2018-03-01 21:00
I experienced significant lag (about 4 seconds or so) between making changes and seeing the gutter updated. I have been using NeoVim (0.2.0) for a while, and I thought that maybe the issue was specific to it. However, I tried updating the plugin in Vim (7.4) and saw the same slowdown. 

Even starting NeoVim with zero other plugins didn't resolve the issues. I also tried with new Git repo with only one commit, and the lag was still there. As others have commented, downgrading to the pre-refactor commit resolved the issues for me.

**Comment by airblade** [comment] 2018-03-01 21:10
What is your `updatetime`?

```
:echo &updatetime
```

**Comment by TyPott** [comment] 2018-03-01 22:19
Whoops, my mistake. I didn't catch that the refactor required a config change. I didn't see anything in the changelog and I hadn't checked the README in months.

Sorry, I was hoping that information would be a little more useful than it ended up being. I'm back on latest now, so I'll check back if I encounter any other issues. Thanks!

**Comment by nomoresecrets** [comment] 2018-03-06 09:18
same issue here with vim 8.0.1543

**Comment by airblade** [comment] 2018-03-06 09:23
@trusktr @relapi @dkarter @brolycjw @nomoresecrets I'm sorry it's intermittently buggy for you.  I use both Vim and NeoVim and I haven't seen any problems, which means I need repro steps or some kind of clue to point me in the right direction.

**Comment by amadeus** [comment] 2018-03-07 22:56
A couple things I've noticed since the update:

1) When using Fugitive to commit and stage files, doesn't seem to trigger updates appropriately in Git Gutter. Perhaps there is some user event I can hook into in Vim Fugitive to fix this?

2) Being unable to stage or unstage hunks from diff mode kinda sucks :( any way to bring that back?

**Comment by airblade** [comment] 2018-03-08 11:38
@amadeus 

1. Ah, good point.  I don't use Fugitive so I forgot about this.  Fugitive fires `BufWritePost` after adding to the index with `GWrite` (https://github.com/tpope/vim-fugitive/commit/57afba5bdd49b59d57485f90aa0cf3f3a6c47f63) but GitGutter no longer listens to this autocommand.  If we could get Fugitive to fire `ShellCmdPost`, GitGutter would update.  Or even a custom Fugitive user autocommand.

2. This was turned off because diff mode caused the [signs to be in the wrong place](https://github.com/airblade/vim-gitgutter/issues/303#issuecomment-220133642).  Did you not run into that?

**Comment by amadeus** [comment] 2018-03-10 01:20
@airblade interesting, I never had the signs in the wrong place in diff mode bug, ever (and I've been using this plugin for a long time)

**Comment by airblade** [comment] 2018-03-16 17:06
@amadeus Hmm, I can no longer reproduce signs being in the wrong place when using `Gdiff`.  Now I'm wondering if there's actually any need at all to disable gitgutter when `&diff` is set – I never set `&diff` so I'm not sure what the consequences are.  Do you have any views?

**Comment by airblade** [comment] 2018-03-16 18:59
@amadeus 37bdd03 restores gitgutter in diff mode.

**Comment by airblade** [comment] 2018-03-21 15:02
@amadeus Re updating after `:GWrite`, I asked about it [here](https://github.com/tpope/vim-fugitive/issues/503#issuecomment-374968526).

**Comment by airblade** [comment] 2018-03-21 15:04
I'm sorry gitgutter is buggy for you but I'm going to close this issue because I can't reproduce the original problem.  Please open a new issue with repro steps if it's still causing you problems.  Thanks.

**Closed by airblade** 2018-03-21 15:04 UTC
