### ISSUE TITLE
gitgutter overwriting all other plugin signs (YCM, signify, syntastic)

### ISSUE THREAD

**Issue by vsilv** [airblade/vim-gitgutter#276] opened 2015-10-20 13:54 UTC
I have the strange behavior that gitgutter is overwriting all other plugins. Maybe it is something system-specific, but I updated to the recent versions of all plugins. Do you know how I can find the problem?

**Comment by airblade** [comment] 2015-10-20 13:57
It shouldn't ever overwrite signs it didn't place itself.

You could try inspecting the content of the `other_signs` list at the end of [this function](https://github.com/airblade/vim-gitgutter/blob/a30ee7f23e93c827b4857d337f04c1ddf3c0c16e/autoload/gitgutter/sign.vim#L70-L102) to see if vim-gitgutter is correctly identifying other plugins' signs.

**Comment by airblade** [comment] 2015-11-17 11:01
Any more information?

**Comment by airblade** [comment] 2015-11-24 11:20
Closing this because there hasn't been any further information and I can't reproduce the problem.

**Closed by airblade** 2015-11-24 11:20 UTC
