### ISSUE TITLE
Custom Signs mess with Visual Select Visualization

### ISSUE THREAD

**Issue by senft** [airblade/vim-gitgutter#284] opened 2015-11-28 12:47 UTC
Hi,
when I define custom signs for GitGutter, e.g.

    let g:gitgutter_sign_added = "＋"
    let g:gitgutter_sign_removed = "－"
    let g:gitgutter_sign_modified = "＊"

lines, that are "highlighted" by GitGutter, somehow display an incorrect background color. Take a look at this screenshot.

![](http://i.imgur.com/I7KW5Ne.png)

On the left, the custom signs are disabled and everything is displayed correctly. On the right I have defined custom signs and lines 312-314 have a black background, even though they are "visually selected" (the selection ranges in both vim instances are the same).

Can someone reproduce this or is this maybe a problem with my colorscheme (vim-hybrid)?

best

**Comment by airblade** [comment] 2015-11-30 10:07
I get the same effect too (with vim-solarized).

At first glance I suspect it's because vim-gitgutter's [highlights](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/highlight.vim) are overriding the colorscheme's `visual` highlights though I'm not sure why.

**Comment by senft** [comment] 2015-11-30 11:16
Also, the custom signs seem to influence the colorcolumn :( Not sure if this might be related...

![](http://imgur.com/l175nKcl.png)

**Comment by airblade** [comment] 2015-11-30 15:05
The problem doesn't manifest for custom signs which are simple ASCII characters.  This makes me think the full-width nature of your signs is breaking vim's highlighting/rendering somehow.

**Comment by senft** [comment] 2015-12-01 09:24
Ah, that makes sense. Too bad...

**Comment by airblade** [comment] 2015-12-01 11:33
I raised this on [vim_use](https://groups.google.com/forum/#!topic/vim_use/XyZ2PQdMitA).

**Comment by airblade** [comment] 2015-12-02 09:54
Closing this because the problem isn't caused by vim-gitgutter – see the vim_use thread linked above where I posted steps to reproduce without vim-gitgutter.

**Closed by airblade** 2015-12-02 09:54 UTC

**Comment by airblade** [comment] 2015-12-03 16:19
Christian Brabandt posted a patch on that vim_use thread which solved both problems for me.

**Comment by senft** [comment] 2015-12-04 11:24
Awesome. Thanks for your dedication!
