### ISSUE TITLE
Highlights only show after re-sourcing vim rc

### ISSUE THREAD

**Issue by imran-iq** [airblade/vim-gitgutter#520] opened 2018-05-10 15:44 UTC
> What is the latest commit SHA in your installed vim-gitgutter?

`a7206c4`

> What vim/nvim version are you on?

```
❯ nvim --version
NVIM v0.2.2
Build type: Release
```

When i open a file with changes it looks like this
![screen shot 2018-05-10 at 11 24 49](https://user-images.githubusercontent.com/624456/39878686-f607c2ec-5446-11e8-93a4-4510572864b0.png)

But after I run `:source $MYVIMRC` it has colors
![screen shot 2018-05-10 at 11 25 51](https://user-images.githubusercontent.com/624456/39878717-0908b40a-5447-11e8-9c3e-9e9c70368ca6.png)

I'm not sure why the colors are not being shown

[my vimrc](https://github.com/imran-iq/dotfiles/blob/master/vim/init.vim)

**Comment by airblade** [comment] 2018-05-11 08:40
What happens if you move your [theme configuration](https://github.com/imran-iq/dotfiles/blob/f3161cf317ba736faaa055e28dc16f1334bde8bb/vim/init.vim#L132-L138) to before you load your plugins?

**Comment by imran-iq** [comment] 2018-05-11 17:31
That doesn't seem to have any effect, nor does changing the order of the plugins

**Comment by airblade** [comment] 2018-05-16 16:11
I can't reproduce this myself and I'm not really sure what's causing the problem.

Does adding this towards the end of your vimrc help?

```
call gitgutter#highlight#define_sign_column_highlight() | call gitgutter#highlight#define_highlights()
```

**Comment by imran-iq** [comment] 2018-05-16 20:29
So removing this line
`Plug 'dracula/vim', { 'as': 'dracula' }`
Causes everything to work as expected for some odd reason 🤷‍♂️

**Comment by airblade** [comment] 2018-05-17 08:33
Well spotted.

It must be something to do with [these lines in dracula](https://github.com/dracula/vim/blob/c01ceb9a8450c736483c916bc30a66d3fe4cbdc4/after/plugin/dracula.vim#L27-L32), and whether they are executed before or after gitgutter is loaded.

**Comment by dsifford** [comment] 2018-05-17 15:12
@imran-iq To confirm: You noticed this issue when you had Dracula installed, but not enabled, correct?

Didn't consider that possibility. I'll work on adjusting for that as well.

**Comment by imran-iq** [comment] 2018-05-17 15:13
@dsifford that is correct, it was in my Plug list, but my `colorscheme` was set to something else

**Comment by airblade** [comment] 2018-05-17 16:39
> why not link the GitGutterXXX groups to the builtin diff groups 

The [line highlight groups](https://github.com/airblade/vim-gitgutter/blob/a7206c41fc174f576b3f7085d48319dbdad760a5/autoload/gitgutter/highlight.vim#L65-L68) are linked to the built in diff groups.  I can't remember for certain why I didn't link the sign highlights to the built in diffs – most probably because I didn't like the default diff colours.

I agree it would make more sense to do this – I'll add it to my list...

**Comment by airblade** [comment] 2018-07-29 07:58
I opened #545 for using the default colours.  I'll close this in the meantime.

**Closed by airblade** 2018-07-29 07:58 UTC

**Comment by airblade** [comment] 2019-02-05 20:53
> I can't remember for certain why I didn't link the sign highlights to the built in diffs

I remember: I chose the colours to match git-diff's colours in my terminal.
