### ISSUE TITLE
Triggers file save when entering modified buiffer

### ISSUE THREAD

**Issue by wjagodfrey** [airblade/vim-gitgutter#412] opened 2017-04-08 06:51 UTC
Hi there,
Happy user of your package for a few years now. Today I updated my vim bundles and noticed that `vim-gitgutter` is autosaving a modified buffer every time I view it. This is kicking off file change monitoring scripts in other parts of my projects, leading to additional processing overhead. I can open NERDTree and close it again, putting me back in the buffer, and it triggers a save. Not good.

Any ideas on resolving this?

Thanks
WIlfred

**Comment by airblade** [comment] 2017-04-08 08:28
Hi Wilfred,

Vim-gitgutter isn't supposed to save modified buffers (and it doesn't for me).  Perhaps one of the other bundles that were updated introduced this autosaving behaviour?

Would you be able to run vim with only vim-gitgutter and see if your modified buffers are still autosaved?

Thanks,
Andy

**Comment by wjagodfrey** [comment] 2017-04-16 00:39
I've confirmed that this happens with a bare vimrc (`vundle`, `vim-gitgutter`)

Most recent version of `vim-gitgutter`

Vim version:

```
> vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 24 2017 17:57:42)
MacOS X (unix) version
Included patches: 1-329
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +float           +mouse_urxvt     +tcl
+autocmd         +folding         +mouse_xterm     +termguicolors
+balloon_eval    -footer          +multi_byte      +terminfo
+browse          +fork()          +multi_lang      +termresponse
++builtin_terms  +fullscreen      -mzscheme        +textobjects
+byte_offset     -gettext         +netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +odbeditor       +toolbar
+clientserver    +insert_expand   +packages        +transparency
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
+file_in_path    +mouse_sgr       +tag_old_static
[...]
```

**Comment by airblade** [comment] 2017-04-18 08:26
Thanks for the extra information.  I still can't reproduce the problem.

I noticed in your normal vimrc you have [autowrite](https://github.com/wjagodfrey/dotfiles/blob/1948dfc9a58ef508bace2ddefac8e0c39927a263/dotfiles/vimrc#L119) switched on, which would cause the behaviour you're seeing.

Do you see the file-saving-on-buffer-switch without vim-gitgutter?

**Comment by wjagodfrey** [comment] 2017-04-18 09:13
As I said, I tested with a bare vimrc. Removing gitgutter resolved the
problem. Confirmed regression of all other plugins.

I can send you my test vimrc in the morning (NZ)

On Apr 18, 2017 8:26 PM, "Andy Stewart" <notifications@github.com> wrote:

Thanks for the extra information. I still can't reproduce the problem.

I noticed in your normal vimrc you have autowrite
<https://github.com/wjagodfrey/dotfiles/blob/1948dfc9a58ef508bace2ddefac8e0c39927a263/dotfiles/vimrc#L119>
switched on, which would cause the behaviour you're seeing.

Do you see the file-saving-on-buffer-switch without vim-gitgutter?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/airblade/vim-gitgutter/issues/412#issuecomment-294727446>,
or mute the thread

**Comment by airblade** [comment] 2017-04-18 11:41
I'm sure your test vimrc is minimal.

Occasionally I hear of vundle appearing to update a repo but not actually doing it.  Would you mind verifying that your gitgutter installation is at 9ecce5a?

And would you have time to git-bisect the repo to identify the commit which introduced the bad behaviour?  I can't think of another way to figure out where the problem is.

**Comment by wjagodfrey** [comment] 2017-04-23 03:27
Ok, the problem exists in every single version of `vim-gitgutter` - going all the way back to `843ee5a - First draft.`

The most minimal `vimrc` I can write that exhibits this is below. Removing the plugin from the vimrc fixes the problem.

My hunch is there's an interop issue between this newer version of `vim`, and `vim-gitgutter`. If you can pull them down and try them out that would be great.

```
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'airblade/vim-gitgutter'

call vundle#end()
```

**Comment by airblade** [comment] 2017-04-24 10:09
I still can't reproduce the problem :/

I'm using (Mac)Vim 8.0p525 built via Homebrew.  I removed all my plugins and my vimrc.  I installed vim-gitgutter into Vim's plugin area (to take Vundle out of the equation):

```sh
cd ~/.vim
mv vimrc vimrc_orig && mv gvimrc gvimrc_orig
mkdir -p pack/bundle/start && cd pack/bundle/start && git clone https://github.com/airblade/vim-gitgutter.git
```

I then went to one of my project repos, opened a file, made some changes without saving, split the window, moved to the other window, opened another file, and moved back to the first window.  Its changes were not saved, as expected.

I needed to split the window and move between the two resulting windows because you can't open a second file in a window with unsaved changes with vim's default settings: you get `E37: No write since last change`.  Presumably you get this error too.

Is it possible you have both a `~/.vimrc` and a `~/.vim/vimrc` and you have only removed one of them?  Grasping at straws, what does `:verbose set autowrite?` give?

**Comment by kubapok** [comment] 2017-04-25 23:03
Hi, 

I've recently discovered gitgutter and I think, it's great.

Unfortunately, I found out, that after previewing a chunk (and undoing as well) whole modified buffer is automatically saved. That's how I found this topic.

Command `:verbose set autowrite?` returns `noautowrite`. I'm on latest commit ( `fd4fa5bed7a306aea758c4cb8c77e7c6e12000b9` )

Soon, I will check if I can reproduce this bug on my computer at work ( I have similar vim config there) and check what can cause that issue.

**Comment by airblade** [comment] 2017-04-26 07:56
@kubapok I've opened a new issue (#417) for that because it's a different problem.  Let's continue the discussion there.

**Comment by enov** [comment] 2017-05-19 17:14
Affected by this as well. Vim saves files after switching buffers. Vim version:
```
❯ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 03 2017 12:11:53)
Included patches: 1-313, 315-596
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
...
```

**Comment by enov** [comment] 2017-05-23 16:20
My bad, I am explicitly saving buffers on BufLeave / FocusLost in my vimrc! Sorry for the noise. Thanks for the awesome plugin!

**Comment by airblade** [comment] 2017-09-22 15:30
@wjagodfrey I can't reproduce this so I'm going to close it unless/until further information comes to light.

**Closed by airblade** 2017-09-22 15:30 UTC
