### ISSUE TITLE
Signs not showing and modifications seemingly not detected

### ISSUE THREAD

**Issue by IanBurganMod** [airblade/vim-gitgutter#747] opened 2020-11-06 21:15 UTC
> What is the latest commit SHA in your installed vim-gitgutter?
987a33355ef424161fdbc4e5d625b5b5aed9704c

> What vim/nvim version are you on?
NVIM v0.4.4

I've tried everything in the trouble shooting section to no avail. Neovim reports my git version as `2.23.0.windows.1`.
When in a file that is clearly modified no signs show. In fact, I'm unable to tell if gitgutter does anything at all. I have it installed via `vim-plug`. The only indications that gitgutter is installed are that there are not errrors when running `:GitGutter...` commands and I have an indicator in my status bar (visible in image below). I'm on Windows and the same behavior is exhibited in both vim and gvim.

Any help would be appreciated.

![image](https://user-images.githubusercontent.com/50185263/98415066-88d10300-204a-11eb-90c9-b79e29629536.png)

**Comment by munnik** [comment] 2020-11-08 02:09
I think I have the same issue.  Version of git-gutter installed is `987a33355ef424161fdbc4e5d625b5b5aed9704c`. Version of NVIM is `NVIM v0.4.4`.
I'm running OpenBSD 6.8.

**Comment by airblade** [comment] 2020-11-09 09:50
Please could you turn on logging with `let g:gitgutter_log=1`, reproduce the problem, then upload the log file (`gitgutter.log` in the directory where the plugin is installed)?  This will tell us whether there's a problem calling out to git-diff.

To see whether any signs have been placed, you can do `:sign place group=gitgutter`.

**Comment by IanBurganMod** [comment] 2020-11-09 22:11
A truncated version of my log is below. The full version doesn't contain anything other than duplicates of the lines below (with other filenames). When I run `:sign place group=gitgutter`, I always get the same result. `--- Signs ---` with nothing below it.
```

==== start log session ====

  0.000014 function <SNR>19_on_bufenter[22]..gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  0.000014 [async] cd /d "X:/Users/MyUser/project/pages" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Modified.js

  0.335783 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  0.335783 [async] cd /d "X:/Users/MyUser/project/pages" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Modified.js

  1.023022 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  1.023022 [async] cd /d "X:/Users/MyUser/project/pages" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Modified.js

  6.960989 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  6.960989 [async] cd /d "X:/Users/MyUser/project/pages" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Modified.js

  7.391530 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  7.391530 [async] cd /d "X:/Users/MyUser/project/pages" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Modified.js

  8.154265 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  8.154265 [async] cd /d "X:/Users/MyUser/project/pages" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Modified.js

  8.874252 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  8.874252 [async] cd /d "X:/Users/MyUser/project/pages" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Modified.js

  9.603709 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  9.603709 [async] cd /d "X:/Users/MyUser/project/pages" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Modified.js

 12.175367 function <SNR>19_on_bufenter[22]..gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 12.175367 [async] cd /d "X:\Users\MyUser\project\components" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Untracked.js

 12.517645 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 12.517645 [async] cd /d "X:\Users\MyUser\project\components" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Untracked.js

149.963026 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
149.963026 [async] cd /d "X:\Users\MyUser\project\components" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Untracked.js

179.402378 function gitgutter#all[8]..gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
179.402378 [async] cd /d "X:\Users\MyUser\project\components" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Untracked.js

179.772324 function gitgutter#process_buffer[10]..<SNR>62_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
179.772324 [async] cd /d "X:\Users\MyUser\project\components" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- Untracked.js
```

**Comment by airblade** [comment] 2020-11-10 09:19
The `git ls-files ...` is gitgutter trying to establish the repo path to the file.

The first set of calls are for `Modified.js` which I presume is tracked by git.  We should see only one `git ls-files` call because after that the path should be cached in a buffer variable.  Please could you do `:echo b:gitgutter.path` – it should give the path to the file but if it's `-2`, it means either the file isn't tracked by git or the `git ls-files` failed.

I would expect to see error messages in the log if `git ls-files` failed, but maybe that assumption is wrong.

I am a little suspicious of the space in `C:\Program Files\...`.  Maybe that needs to be escaped with a backslash?

**Comment by IanBurganMod** [comment] 2020-11-10 15:18
`:echo b:gitgutter.path` did indeed return `-2`.

Everything seems to be working as expected after removing `let g:gitgutter_git_executable = 'C:\Program Files\Git\bin\git.exe'` from my vimrc. I tried various ways of escaping the space, but none of them seem to work. I tried `^` before the space, but that caused gitgutter to never even load. A backslash won't work because those are used between directories. I tried `let g:gitgutter_git_executable = '"C:\Program Files\Git\bin\git.exe"'` but that also caused gitgutter to never load. Ultimately, the issue described in the readme doesn't really apply to me as I don't have any files named `git.*`.

It would probably be best to alter the [Windows](https://github.com/airblade/vim-gitgutter#windows) section of the readme as that seems to be the cause behind all this. I'm happy to test potential solutions you have for the issue described in that section should you come up with any.

**Comment by airblade** [comment] 2020-11-10 15:25
What does `:echo fnameescape('C:\Program Files\Git\bin\git.exe')` produce?

**Comment by IanBurganMod** [comment] 2020-11-10 15:28
It produces `C:\Program\ Files\Git\bin\git.exe`.

**Comment by airblade** [comment] 2020-11-10 15:34
>  A backslash won't work because those are used between directories.

Did you actually try it?  `let g:gitgutter_git_executable = 'C:\Program\ Files\Git\bin\git.exe'`

**Comment by IanBurganMod** [comment] 2020-11-10 15:37
Yes. I've just confirmed. After putting `let g:gitgutter_git_executable = 'C:\Program\ Files\Git\bin\git.exe'`, I lose the numbers in my status bar and `:GitGutterEnable` results in `E492: Not an editor command: GitGutterEnable`. So it seems to be failing even earlier than without the backslash.

**Comment by airblade** [comment] 2020-11-10 16:45
Weird.  One last question: what does `:echo exepath('git.exe')` produce (without having set `g:gitgutter_git_executable`)?

**Comment by IanBurganMod** [comment] 2020-11-10 16:53
It returns `C:\Program Files\Git\cmd\git.exe`. In fact, it returns this even when I set `g:gitgutter_git_executable` to be the exe in the `bin` directory for what it's worth.

**Comment by airblade** [comment] 2020-11-11 09:50
So there's a `git.exe` in both `C:\Program Files\Git\cmd\` and `C:\Program Files\Git\bin\`?

I was hoping the `exepath()` output would show what escaping we need to do, but evidently not.

I've just thought of one more thing to try: use forward slashes.  I know it sounds odd but it worked [here](https://github.com/airblade/vim-gitgutter/issues/421#issuecomment-472257680).

```viml
let g:gitgutter_git_executable = 'C:/Program Files/Git/bin/git.exe'
```

**Comment by airblade** [comment] 2020-11-11 09:58
> Everything seems to be working as expected after removing let g:gitgutter_git_executable = 'C:\Program Files\Git\bin\git.exe' from my vimrc... Ultimately, the issue described in the readme doesn't really apply to me as I don't have any files named git.*.

Given that, I'm going to close this issue.

**Closed by airblade** 2020-11-11 09:58 UTC

**Comment by IanBurganMod** [comment] 2020-11-11 14:20
There is a `git.exe` in both of the locations. Also, for anyone who stumbles upon this issue, forward slashes did not work for me. It exhibited the same behavior as what I was experiencing initially.

@airblade Thanks for all the help troubleshooting 👍
