### ISSUE TITLE
vim-gitgutter takes like 3 seconds to load up the results. What could be causing it?

### ISSUE THREAD

**Issue by hellovimo** [airblade/vim-gitgutter#791] opened 2021-07-07 13:46 UTC
> What is the latest commit SHA in your installed vim-gitgutter?
0f98634b92da9a35580b618c11a6d2adc42d9f90

> What vim/nvim version are you on?
vim - 7.4

I have the vim-gitgutter installed in my system. I have the below code enabled for the same in the .vimrc.

`let g:gitgutter_realtime = 1
  let g:gitgutter_eager = 1
  let g:gitgutter_highlight_lines = 1
  let g:gitgutter_highlight_linenrs = 1 `

But even if I remove the first two lines of the above code, still I see the vim shows the updates made without even saving the files. So, that adds to doubt, if any change that I make in .vimrc for gitgutter is taking into effect or not ? If so, is it loading up any default values?

When I open any of my git related files which are already edited, it takes like 3 seconds to show up the git changes in the file. Also even when I add any new updates, it takes like 3 seconds to show up the changes onto the file.

Any guess what could be the reason for this slowness? could it be the .vimrc? or anything else?

**Comment by airblade** [comment] 2021-07-07 14:28
What does `:echo &updatetime` say?  It sounds like it's the default `4000`.  If so, try setting it to, say, `100`.

Also, `g:gitgutter_realtime` and `g:gitgutter_eager` were removed ages ago so setting them won't do anything.

**Comment by hellovimo** [comment] 2021-07-07 14:57
Thanks a lot for super quick response.  Yes, it was default set to 4000 and after setting set updatetime=100 it was able to load up quickly. 

But one thing I noticed is that, after loading any vim file the gitgutter updates didn't show up until I moved the cursor in the keyboard [up/down button]. Is this known behavior ?

Also is there any page where I can find all the active settings that can be made ? Or whatever that's listed in this page is the active ones ?

**Comment by airblade** [comment] 2021-07-07 15:09
When you load/move into a buffer, the diff signs should show immediately.  After that, they update whenever the cursor moves.

What specific patch level is your vim?  In other words, what is the full version number?

You can see all the settings in the README and also with `:help gitgutter-options`.

**Comment by hellovimo** [comment] 2021-07-07 15:11
Thanks a lot for the response. 

Vim - Version & Patch. Is this what you requested for ?
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 20 2017 04:38:11)
Included patches: 1-160

**Comment by airblade** [comment] 2021-07-07 15:14
Try `let g:gitgutter_terminal_reports_focus=0`.

**Comment by hellovimo** [comment] 2021-07-07 15:21
Think its not working. Until I move the cursor up/down using keyboard or click using the mouse the git-gutter isn't loading up the changes in the version 7.4. But in vim8.2 it loads up immediately. Anyways that would help. Thanks a lot for your quick response. 

BTW, I have this setting
let g:gitgutter_highlight_linenrs=1 in my .vimrc, but don't see the line numbers being highlighted. Is this set by default or the user needs to set ?

**Comment by airblade** [comment] 2021-07-07 15:49
> Until I move the cursor up/down using keyboard or click using the mouse the git-gutter isn't loading up the changes in the version 7.4.

Is this only when starting vim with a file, or is it every time you move into a buffer?

> don't see the line numbers being highlighted

Vim doesn't support that, only Neovim.

**Comment by hellovimo** [comment] 2021-07-07 17:25
> > Until I move the cursor up/down using keyboard or click using the mouse the git-gutter isn't loading up the changes in the version 7.4.
> 
> Is this only when starting vim with a file, or is it every time you move into a buffer?
> 
> > don't see the line numbers being highlighted
> 
> Vim doesn't support that, only Neovim.

**Comment by hellovimo** [comment] 2021-07-07 17:28
Sorry by mistake closed it.

1. This is when I start the vim with a file. move into a buffer meaning ?
2. Oh okies.. Thought vim as well supports it.

**Comment by airblade** [comment] 2021-07-07 17:44
Thanks for the info.  

You can have many files open in Vim at the same time.  Vim has a "buffer" for each file, and each buffer can have zero, one, or more windows (Vim windows, not OS windows) looking at it.  See `:help windows` for more information.  By "moving into a buffer" I meant bringing a different buffer into the current window or moving your cursor to a different window.

Adding `let g:gitgutter_terminal_reports_focus = 0` to your vimrc should make signs appear immediately when you launch Vim with a file on Vim 7.4.160.

You can check the value of any gitgutter option with `:echo g:gitgutter_name_of_variable`.  There is a log but it doesn't write out the plugin's options' values.

The documentation I mentioned earlier describes all the default values and you can also look at the initialisation [here](https://github.com/airblade/vim-gitgutter/blob/0f98634b92da9a35580b618c11a6d2adc42d9f90/plugin/gitgutter.vim#L24-L93).

**Comment by hellovimo** [comment] 2021-07-07 18:21
Hello !

1. When I try :echo g:gitgutter_highlight_lines, the echo prints 1 i.e. enabled, but I don't see the modified lines getting highlighted.
2. But once I type in the vim file, :GitGutterLineHighlightsEnable, then the modified lines gets highlighted. But not through the default enable in the .vimrc

Is this because of vim version ? or does it mean, not picking up the gitgutter ?

**Comment by airblade** [comment] 2021-07-08 10:40
It's not because you're using a really old Vim – it should still work.

What does this produce?

```viml
:sign list GitGutterLineAdded
```

**Comment by hellovimo** [comment] 2021-07-08 20:04
Helllo @airblade This is what I see when I type the above command which you asked.

`sign GitGutterLineAdded text=+  linehl= texthl=GitGutterAdd`

**Comment by airblade** [comment] 2021-07-10 08:55
The `linehl=` shows that the line highlight has not been set.  I'm not sure why.

Is your up-to-date vimrc online somewhere?

**Comment by hellovimo** [comment] 2021-07-11 07:15
Hello @airblade You can find the same in the below git repository. Let me know if you able to access the same. 
https://github.com/hellovimo/vim/blob/main/.vimrc

**Comment by airblade** [comment] 2021-07-12 10:01
Thanks.

I don't know why the `linehl` sign attribute is not set despite `let g:gitgutter_highlight_lines = 1` in your vimrc – it doesn't make any sense.  Your vimrc is read before any plugins are loaded, yet something is clearing the variable by the time the plugin loads.

I don't have a Vim 7.4 I can debug this with so I'm out of ideas, sorry.  As this is a minor issue with a very obsolete version of Vim, and the original issue is resolved, I'm going to close this.

**Closed by airblade** 2021-07-12 10:01 UTC

**Comment by hellovimo** [comment] 2021-07-12 15:10
Sure @airblade  thanks for all your help and explanation. Think I had similar issue in latest vim8.2 as well. Is it possible for you to check in the updated version ?

**Comment by airblade** [comment] 2021-07-12 15:11
I cannot reproduce the problem in a recent Vim.

**Comment by hellovimo** [comment] 2021-07-12 17:34
Thanks @airblade appreciate your help on this.
