### ISSUE TITLE
Add option to stash hunk under cursor

### ISSUE THREAD

**Issue by Bubu** [airblade/vim-gitgutter#432] opened 2017-08-14 10:20 UTC
Like undoing and staging a hunk, sometimes it is necessary to stash a specific hunk (whjich you can do with git stash -p).

Would it be possible to add a keybinding to do this to gitgutter?

**Comment by airblade** [comment] 2017-08-14 16:21
Yes, that would be possible.  I'm away for a bit but can do this when I'm back.

Thanks for the suggestion!

**Comment by kabouzeid** [comment] 2017-08-22 11:05
I could need this too

**Comment by airblade** [comment] 2018-02-20 14:20
I have been looking into this.  The problem is that `git stash -p` only runs interactively, which is no good in this situation.

You can drive the interactive responses non-interactively (e.g. `printf "%s\n" n y n n | git stash -p`) if you know which hunk you want, which we do, but there's another problem: `git stash -p` seems to require hunks to be separated by three unchanged lines.  If you have two hunks separated by one or two unchanged lines, `git stash -p` initially shows one big hunk; although you can split it in two, the second stash fails to complete.

A workaround would be only to allow stashing of hunks separated by 3+ unchanged lines from the next hunk, but that's inconsistent with gitgutter's other hunk operations.

Magit takes a different approach: stage what you want to stash, then stash the index.  The tricky part is restoring the state of the index and working tree afterwards.  I don't yet understand their implementation.

Any suggestions would be appreciated.  In the meantime I'll keep researching.

**Comment by airblade** [comment] 2018-02-20 16:32
I've got something that seems to work:

1. Remove the hunk-we-want-to-stash from the buffer.
2. Remove the hunk from its file (if it's in the file).
3. Stash everything so we can restore it at the end.
4. Apply hunk back to its file.
5. Stash.  This is the stash we want.
6. Restore everything else from step 3.

The only remaining problem is that because the file changes outside vim, when you come to save your buffer, vim puts up a warning and requires confirmation:

```
WARNING: The file has changed since reading it!!!
Do you really want to write to it (y/n)?
```

**Comment by kabouzeid** [comment] 2018-02-20 22:51
Trickier than I thought. The proposed solution seems hacky though. Not sure if there are any cases where this could go wrong.

**Comment by airblade** [comment] 2018-02-21 08:53
There are several steps but the method looks robust to me.  The plugin can already do step 1 (in the undo hunk operation); steps 3 to 6 are standard git; step 2 is also standard git but I want to test further what happens when the hunk isn't in the file.

**Comment by airblade** [comment] 2019-01-25 17:36
Closing this because I think it's a rare use case and not worth the complexity.

**Closed by airblade** 2019-01-25 17:36 UTC
