### ISSUE TITLE
Gitgutter crashing randomly

### ISSUE THREAD

**Issue by cody-code-wy** [airblade/vim-gitgutter#347] opened 2016-06-02 23:43 UTC
Sometimes when switching between buffers/tabs/splits, saving, or quitting this shows up.

Crashlog
```
Error detected while processing function gitgutter#process_buffer[10]..gitgutter#diff#run_diff[73]..gitgutter#utility#system:
line   12:
E484: Can't open file /var/folders/t0/3nvr9y9s7yz4h_s8042bjbyw0000gn/T/vyOYMR2/115
Press ENTER or type command to continue
```

I have `set shell=/bin/zsh` in my vimrc, but after this error if I `:echo &shell` after this error it is `/bin/sh` but before it is `/bin/zsh`. However `set shell=/bin/sh` does not cause the problem to reproduce.

**Comment by airblade** [comment] 2016-06-03 09:36
I'm away this week but will investigate when I'm back.

In the meantime you could `let g:gitgutter_log=1`, reproduce the error and look for the log file in vim-gitgutter's directory.

**Comment by jamesmlees** [comment] 2016-06-06 08:20
I'm seeing this too after upgrading from 7.3 to 7.4!

**Comment by airblade** [comment] 2016-06-06 08:35
@cody-code-wy E484 generally means that Vim can't run an external command via `system()` for whatever reason.  As of 377c71d the code sets the `&shell` option to `/bin/sh` – what does `/bin/sh` point to on your system?

It would help to have the log file too at the point of a crash.  Also the output of `:GitGutterDebug`.

Can you reproduce the crash consistently?

@jamesmlees That's weird.  What system are you on?

**Comment by jamesmlees** [comment] 2016-06-06 08:42
@airblade might not be related to version. I just migrated from system vim on OSX to vim installed via brew.
`VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 28 2015 19:46:19)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
`

`
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  5 2016 17:43:01)
MacOS X (unix) version
Included patches: 1-1830
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +termguicolors
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+channel         -gettext         -mzscheme        +textobjects
+cindent         -hangul_input    +netbeans_intg   +timers
-clientserver    +iconv           +packages        +title
+clipboard       +insert_expand   +path_extra      -toolbar
+cmdline_compl   +job             +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/Users/jameslees/.rbenv/versions/2.2.2/lib  -fstack-protector -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.10_2/Frameworks -framework Python   -lruby-static -framework CoreFoundation -lgmp -lobjc -L/Users/jameslees/.rbenv/versions/2.2.2/lib
`

**Comment by airblade** [comment] 2016-06-06 08:57
@jamesmlees I use MacVim installed via Homebrew on OS X too and haven't seen this error.  Please could you enable the log (as described above) and gist the log when the plugin next crashes?  Also the output of `:GitGutterDebug` would help.

**Comment by jamesmlees** [comment] 2016-06-06 09:09
@airblade sure. It actually seems weirdly inconsistent. Will keep an eye on it and see if I can try to see what specific conditions trigger the error. 
In the meantime, here's the output of  `:GitGutterDebug" 

Thanks for your support 😃 

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  5 2016 17:43:01)
MacOS X (unix) version
Included patches: 1-1830

git version 2.8.1

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]	[-e pattern] [-f file] [--binary-files=value] [--color=when]	[--context[=num]] [--directories=action] [--label] [--line-buffered]	[--null] [pattern] [file ...]

updatetime=2000
shell=/bin/bash
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

**Comment by cody-code-wy** [comment] 2016-06-06 23:13
@airblade the inconsistency described by @jamesmlees is happening on my setup as well.

I am using the terminal version of vim provided in the macvim app.

I have a [gitgutter log](https://gist.github.com/4321c909dd333d26a1513eb85fdf0a60) that contains several of such crashes. the **second to last session** contains a crash. There are also several other crashes there, but I could not point them all out to you. 

The crash actually happens sometimes when not in a git repository. It does not appear that being in a repo affects the crash at all.

`/bin/sh` on my system exists the `--version` output is
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

the output of `:GitGutterDebug` on my system is

```

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  2 2016 15:07:35)
MacOS X (unix) version
Included patches: 1-1089

git version 2.6.4 (Apple Git-63)

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]	[-e pattern] [-f file] [--binary-files=value] [--color=when]	[--context[=num]] [--directories=action] [--label] [--line-buffered]	[--null] [pattern] [file ...]

updatetime=4000
shell=/bin/zsh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

Vim version

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  2 2016 15:07:35)
MacOS X (unix) version
Included patches: 1-1089
Compiled by MacPorts
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_binary
+arabic          +find_in_path    -mouse_sysmouse  +tag_old_static
+autocmd         +float           +mouse_urxvt     -tag_any_white
+balloon_eval    +folding         +mouse_xterm     -tcl
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+cindent         +gettext         +netbeans_intg   +title
+clientserver    -hangul_input    +odbeditor       +toolbar
+clipboard       +iconv           +path_extra      +transparency
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
-cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
+farsi           +mouse_netterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/opt/local/MacVim.app/Contents/Resources/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -I/opt/local/include -DMACOS_X_UNIX  -pipe -Os -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -lintl -framework Cocoa  -L/opt/local/lib -llua  
```

**Comment by cody-code-wy** [comment] 2016-06-07 21:56
@jamesmlees do you by any chance have Unclutter installed on your mac? I notices that the temporary folder it claims to not be able to access is always a non existence child to a temp directory owned by unclutter.

**Comment by cody-code-wy** [comment] 2016-06-07 21:57
I am going to see if the error still reproduces when unclutter is not installed.

**Comment by airblade** [comment] 2016-06-08 06:34
@cody-code-wy That sounds like a plausible cause.

**Comment by jamesmlees** [comment] 2016-06-08 07:49
@cody-code-wy I don't have unclutter installed.

I haven't seen the error for a couple of days so I'm quietly hopeful that this has resolved itself for me.

**Comment by airblade** [comment] 2016-06-08 08:03
@jamesmlees Fingers crossed it's fixed for you!

@cody-code-wy Do you have the same vim instance running for days at a time?  Perhaps the OS is cleaning up the temp directory and deleting vim's temp files out from under it.

**Comment by cody-code-wy** [comment] 2016-06-08 15:34
@airblade it would appear that unclutter just happened to create a temp folder with the same name, as the same issue has persisted since removing it.

I normally don't have vim open for more than a few hours, but it does appear that the os is cleaning the temp directory. there may be a link to allowing the computer to go to sleep… but I have no idea right now.

**Comment by airblade** [comment] 2016-06-09 08:51
@cody-code-wy The penultimate session of your gitgutter.log shows something I don't yet understand: it appears you were editing an untracked file called `practice.sql` but in the realtime diffs it's trying to find a file called `.gitpractice.sql` in the index.

It's also trying to run realtime diffs on the untracked file which, though harmless, is something we could probably stop as an optimisation.

Example log entry:

```
186.279511 cd . && (git ls-files --error-unmatch practice.sql && (git show :'fatal: Not a git repository (or any of the parent directories): .gitpractice.sql' > /var/folders/t0/3nvr9y9s7yz4h_s8042bjbyw0000gn/T/vUyzzPH/2.sql && git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0   -- /var/folders/t0/3nvr9y9s7yz4h_s8042bjbyw0000gn/T/vUyzzPH/2.sql /var/folders/t0/3nvr9y9s7yz4h_s8042bjbyw0000gn/T/vUyzzPH/3.sql | grep --color=never -e '^@@ ' || exit 0))
```

**Comment by cody-code-wy** [comment] 2016-06-10 01:12
@airblade I have updated to the latest commit. I will see if I can reproduce the error now.

**Comment by cody-code-wy** [comment] 2016-06-12 20:06
Ok so I have been able to reproduce the error several time, however I have found that manually creating the folder that it complains about not being able to open, results in restored operation. @airblade I think that perhaps since the temp folder is normally empty that OS X decides that it is not in use.

**Comment by airblade** [comment] 2016-06-13 09:46
According to [this SuperUser answer](http://superuser.com/a/187105) OS X deletes temp files and empty directories after 3 days of inactivity.  On my OS X 10.11.5 the script is `/etc/periodic/daily/110.clean-tmps`.

Do the errors only occur when you use Vim for the first time after 3 days?

Maybe there's a bug in the way Vim handles temp files and missing temp directories.

**Comment by airblade** [comment] 2016-06-13 09:58
I was just re-reading the help docs for `tempfile` and found this sentence:

> When Vim exits the directory and all files in it are deleted.

This makes me wonder whether the following scenario is possible:

1. Edit some files in MacVim.
2. Launch a second MacVim instance and edit some files.  This one uses the same temp directory as the first one.
3. Close one of the MacVim instances.  As it exits it deletes the temp directory it was using.
4. The remaining MacVim instance can no longer access the temp directory and throws an E484.

**Comment by cody-code-wy** [comment] 2016-06-13 15:46
@airblade The problem happens several times a day, so I have to wonder if it has something to do with opening files from a different directory (not nested), or frequent backgrounding of vim.

**Comment by airblade** [comment] 2016-06-13 16:00
I almost always keep Vim in the foreground (MacVim gui) so if there were a problem with frequent backgrounding and tempfile deletion I wouldn't run into it.

Do you get the problem straight after bringing vim back to the foreground?

I wouldn't be at all surprised if vim's tempfile code has a bug in it somewhere...

**Comment by tsrivishnu** [comment] 2016-06-16 09:19
I had this issue after having MacVim (GUI) opened for about a week from within the project directory. 

During the week, I haven't made any changes to the files in the project but the vim was left open which I didn't notice as it was on a separate desktop space. However, I was editing other config files with vim once in a while. I quit the open vim after a week and re-opened the project to edit files, it shows me the error.

I didn't have time to read through this to debug the issue. I did a system restart and gitgutter doesn't show any error now.

**Comment by airblade** [comment] 2016-06-16 11:37
@tsrivishnu Almost certainly this is due to OS X cleaning the temp directory.

I'm beginning to think we might avoid some of these problems were the plugin to use its own temp directory, e.g. `~/.vim-gitgutter`, to store its temp files instead of the system one

**Comment by tsrivishnu** [comment] 2016-06-20 11:07
I can confirm that this happens (to me at least) because of the temp directory cleaning by OS X. For some reason, I didn't have to wait for three days, my MacVim session was open and inactive for about 20 hours and this happened.  Restarting MacVim got everything to normal.

@airblade Using its own temp directory would be nice. Of course, I hope gitgutter would clean the directory itself.

**Comment by airblade** [comment] 2016-06-21 10:02
@tsrivishnu This really seems like (a) a problem with the OS cleaning the temp directory too soon, and (b) Vim not being able to handle it.  I think it's out of scope for this plugin.  And I don't want to try to implement my own version of a temp directory.

**Closed** 2016-09-14 15:30 UTC
