### ISSUE TITLE
GitGutterPreviewHunk needs to be called twice if g:loaded_matchparen is set

### ISSUE THREAD

**Issue by astier** [airblade/vim-gitgutter#728] opened 2020-08-01 11:23 UTC
> What is the latest commit SHA in your installed vim-gitgutter?

62ff20f

> What vim/nvim version are you on?

`nvim v0.4.3`

### Problem

When `let g:loaded_matchparen = 0` is set then `GitGutterPreviewHunk` doesn't show anything when its called the first time. It shows the preview of the current hunk only if its called the second time. This means in order to see the preview of the current hunk `GitGutterPreviewHunk` needs to be called twice. If `let g:loaded_matchparen = 0`  is not set then `GitGutterPreviewHunk` works as intended on the first call.

### Minimal vimrc

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
Plug 'airblade/vim-gitgutter'
cal plug#end()
let g:loaded_matchparen = 0
```

**Comment by airblade** [comment] 2020-08-04 15:45
I can't reproduce this in nvim v0.5.0.  For me, `GitGutterPreviewHunk` works first time regardless of `g:loaded_matchparen`'s value.

**Comment by astier** [comment] 2020-08-04 22:43
I tested it right now on nvim v0.5.0 f26df8bb6 and still happens. Maybe I wasn't clear in my instructions. Just to clarify. I meant that the following example causes the issue because `g:loaded_matchparen` is set regardless of the value:

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
Plug 'airblade/vim-gitgutter'
cal plug#end()
let g:loaded_matchparen = 0
```

If its commented out or deleted completly from the config then `GitGutterPreviewHunk` works as expected:

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
Plug 'airblade/vim-gitgutter'
cal plug#end()
"let g:loaded_matchparen = 0
```

or 

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
Plug 'airblade/vim-gitgutter'
cal plug#end()
```

**Comment by airblade** [comment] 2020-08-05 11:36
The `g:loaded_matchparen` variable comes from the built-in [matchparen plugin](https://github.com/vim/vim/blob/fdac71c5075062f97f77044e9619fa5c907e0327/runtime/plugin/matchparen.vim#L9-L12).

If you have `let g:loaded_matchparen = 0` (or `= 1`) in your vimrc/init.vim then the matchparen plugin will not load.

So your error occurs when the matchparen plugin is not loaded and doesn't occur when it has loaded.  Which is weird.

vim-gitgutter doesn't do anything at all with matchparen.  The only thing I can think of is that the matchparen plugin moves the cursor when calculating its matches, which causes gitgutter to close the preview window (if it's a floating window).  But that theory depends on the matchparen plugin causing your problem, yet it's the opposite: the absence of the matchparen plugin causes the problem.

Anyway, I cannot reproduce this with vim-gitgutter as my only plugin and `let g:loaded_matchparen=0` in my vimrc.

What happens if you have `let g:gitgutter_preview_win_floating=0` in your init.vim?

**Comment by astier** [comment] 2020-08-05 11:59
With `let g:gitgutter_preview_win_floating=0` the preview-window is opened on the first try and works as expected. If you can not reproduce it then lets finish this issue. I can set the highlight-group for matchparen such that no highlighting occurs to get around the issue. You can close the issue if you want.

**Comment by airblade** [comment] 2020-08-05 12:17
Let's keep this open a little longer.

I suspect the floating window is opened on the first try but then closed immediately.  You could verify like this:

```diff
diff --git i/autoload/gitgutter/hunk.vim w/autoload/gitgutter/hunk.vim
index 7d4b6e1..fb60856 100644
--- i/autoload/gitgutter/hunk.vim
+++ w/autoload/gitgutter/hunk.vim
@@ -412,6 +412,7 @@ endfunction
 " Floating window: does not move cursor to floating window.
 " Preview window: moves cursor to preview window.
 function! s:open_hunk_preview_window()
+  echom 'open'
   if g:gitgutter_preview_win_floating
     if exists('*nvim_open_win')
       call s:close_hunk_preview_window()
```

The question is then why is the window closing immediately?  Once the window is opened the plugin sets up an autocommand to close it on `CursorMoved`:

https://github.com/airblade/vim-gitgutter/blob/82f3ea6a40b4589eae769b46912e41c5aa0f43bc/autoload/gitgutter/hunk.vim#L436

You could see whether that is activating like this:

```diff
diff --git i/autoload/gitgutter/hunk.vim w/autoload/gitgutter/hunk.vim
index 7d4b6e1..73e28ea 100644
--- i/autoload/gitgutter/hunk.vim
+++ w/autoload/gitgutter/hunk.vim
@@ -433,7 +433,7 @@ function! s:open_hunk_preview_window()
       call nvim_buf_set_name(buf, 'gitgutter://hunk-preview')
 
       " Assumes cursor is in original window.
-      autocmd CursorMoved <buffer> ++once call s:close_hunk_preview_window()
+      autocmd CursorMoved <buffer> ++once echom 'close' | call s:close_hunk_preview_window()
 
       return
     endif
```

**Comment by airblade** [comment] 2020-08-05 12:23
Also, do you have the problem if you eliminate vim-plug?  I wonder if there's a load-order issue.

```vim
syntax enable
filetype plugin indent on
set runtimepath^=$XDG_DATA_HOME.'/nvim/plugins/airblade/vim-gitgutter'
set updatetime=100
let g:loaded_matchparen=0
```

**Comment by astier** [comment] 2020-08-05 18:55
```vim
syntax enable
filetype plugin indent on
set runtimepath^=$XDG_DATA_HOME.'/nvim/plugins/airblade/vim-gitgutter'
set updatetime=100
let g:loaded_matchparen=0
```

Doesn't seem to load gitgutter. First of all it has to be `$XDG_DATA_HOME.'/nvim/plugins/vim-gitgutter'`. But then still gitgutter doesn't seem to be loaded.

> I suspect the floating window is opened on the first try but then closed immediately.

It does echo `open` on the first `GitGutterPreviewHunk`.

> The question is then why is the window closing immediately? Once the window is opened the plugin sets up an autocommand to close it on CursorMoved.

`close` is also echoed immediately after the first `GitGutterPreviewHunk` even tho I can not see a window. On the second `GitGutterPreviewHunk` it opens the window and only echoes `close` after I close it myself.

Your theory that it gets opened and closed immediately seems to be right.

**Comment by airblade** [comment] 2020-08-06 07:12
The window is closed by the CursorMoved autocmd mentioned above.  Presumably, then, something is moving the cursor.  It's not vim-gitgutter (otherwise the window would always be closed straightaway).

**Comment by astier** [comment] 2020-08-06 07:51
I will try it out sometimes again and report if this still happens.

**Comment by airblade** [comment] 2020-08-06 09:34
The strange thing is that the window only closes immediately once; the second time is fine.

Anyway, you could try this:

1. Open a file and go to a hunk.
2. `:set verbose=9 | GitGutterPreviewHunk`

Hopefully this will tell you exactly what is going on.

**Comment by astier** [comment] 2020-08-06 14:11
I tried it again without the vim-plug. The issue is still there.

```vim
set runtimepath^=~/.local/share/nvim/plugins/vim-gitgutter/
let g:loaded_matchparen=0
```

First execution of `set verbose=9 | GitGutterPreviewHunk`

```
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
Executing FileType Autocommands for "*"
autocommand call s:LoadFTPlugin()
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/runtime/ftplugin)
chdir(/home/aleks/projects/dotfiles)
line 17: sourcing "/home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim
continuing in function <SNR>3_LoadFTPlugin
Executing FileType Autocommands for "*"
autocommand call s:LoadIndent()
not found in 'runtimepath': "indent/diff.vim"
Executing FileType Autocommands for "*"
autocommand exe "set syntax=" . expand("<amatch>")
Executing Syntax Autocommands for "*"
autocommand call s:SynSet()
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/runtime/syntax)
chdir(/home/aleks/projects/dotfiles)
line 24: sourcing "/home/aleks/.local/share/nvim/runtime/syntax/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/syntax/diff.vim
continuing in function <SNR>6_SynSet
Executing BufFilePre Autocommands for "*"
autocommand GitGutterBufferDisable
Executing BufFilePost Autocommands for "*"
autocommand GitGutterBufferEnable
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter)
chdir(/home/aleks/projects/dotfiles)
line 24: sourcing "/home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter/diff_highlight.vim"
finished sourcing /home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter/diff_highlight.vim
continuing in function gitgutter#hunk#preview[3]..<SNR>36_hunk_op[62]..<SNR>36_preview[6]..<SNR>36_populate_hunk_preview_window
Executing CursorMoved Autocommands for "<buffer=1>"
autocommand call s:close_hunk_preview_window()
```

Second execution of `GitGutterPreviewHunk`

```
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
Executing FileType Autocommands for "*"
autocommand call s:LoadFTPlugin()
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/runtime/ftplugin)
chdir(/home/aleks/projects/dotfiles)
line 17: sourcing "/home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim
continuing in function <SNR>3_LoadFTPlugin
Executing FileType Autocommands for "*"
autocommand call s:LoadIndent()
not found in 'runtimepath': "indent/diff.vim"
Executing FileType Autocommands for "*"
autocommand exe "set syntax=" . expand("<amatch>")
Executing Syntax Autocommands for "*"
autocommand call s:SynSet()
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/runtime/syntax)
chdir(/home/aleks/projects/dotfiles)
line 24: sourcing "/home/aleks/.local/share/nvim/runtime/syntax/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/syntax/diff.vim
continuing in function <SNR>6_SynSet
Executing BufFilePre Autocommands for "*"
autocommand GitGutterBufferDisable
auto-removing autocommand: BufWriteCmd <buffer=2>
Executing BufFilePost Autocommands for "*"
autocommand GitGutterBufferEnable
```

**Comment by astier** [comment] 2020-08-06 14:20
Heres the output again for the following vimrc:

```vim
syntax enable
filetype plugin indent on
set runtimepath^=~/.local/share/nvim/plugins/vim-gitgutter/
set updatetime=100
let g:loaded_matchparen=0
```

```
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
Executing FileType Autocommands for "*"
autocommand exe "set syntax=" . expand("<amatch>")
Executing Syntax Autocommands for "*"
autocommand call s:SynSet()
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/runtime/syntax)
chdir(/home/aleks/projects/dotfiles)
line 24: sourcing "/home/aleks/.local/share/nvim/runtime/syntax/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/syntax/diff.vim
continuing in function <SNR>3_SynSet
Executing FileType Autocommands for "*"
autocommand call s:LoadFTPlugin()
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/runtime/ftplugin)
chdir(/home/aleks/projects/dotfiles)
line 17: sourcing "/home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim
continuing in function <SNR>6_LoadFTPlugin
Executing FileType Autocommands for "*"
autocommand call s:LoadIndent()
not found in 'runtimepath': "indent/diff.vim"
Executing BufFilePre Autocommands for "*"
autocommand GitGutterBufferDisable
Executing BufFilePost Autocommands for "*"
autocommand GitGutterBufferEnable
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter)
chdir(/home/aleks/projects/dotfiles)
line 24: sourcing "/home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter/diff_highlight.vim"
finished sourcing /home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter/diff_highlight.vim
continuing in function gitgutter#hunk#preview[3]..<SNR>36_hunk_op[62]..<SNR>36_preview[6]..<SNR>36_populate_hunk_preview_window
Executing CursorMoved Autocommands for "<buffer=1>"
autocommand call s:close_hunk_preview_window()

chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/projects/dotfiles)
chdir(dotfiles/nvim)
chdir(/home/aleks/projects/dotfiles)
Executing FileType Autocommands for "*"
autocommand exe "set syntax=" . expand("<amatch>")
Executing Syntax Autocommands for "*"
autocommand call s:SynSet()
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/runtime/syntax)
chdir(/home/aleks/projects/dotfiles)
line 24: sourcing "/home/aleks/.local/share/nvim/runtime/syntax/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/syntax/diff.vim
continuing in function <SNR>3_SynSet
Executing FileType Autocommands for "*"
autocommand call s:LoadFTPlugin()
chdir(/home/aleks/projects/dotfiles)
chdir(/home/aleks/.local/share/nvim/runtime/ftplugin)
chdir(/home/aleks/projects/dotfiles)
line 17: sourcing "/home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim
continuing in function <SNR>6_LoadFTPlugin
Executing FileType Autocommands for "*"
autocommand call s:LoadIndent()
not found in 'runtimepath': "indent/diff.vim"
Executing BufFilePre Autocommands for "*"
autocommand GitGutterBufferDisable
auto-removing autocommand: BufWriteCmd <buffer=2>
Executing BufFilePost Autocommands for "*"
autocommand GitGutterBufferEnable
```

**Comment by airblade** [comment] 2020-08-06 14:50
Thanks for all that.  I still can't tell what the problem is though.

Does this help?

```diff
diff --git i/autoload/gitgutter/hunk.vim w/autoload/gitgutter/hunk.vim
index 7d4b6e1..06fd3ae 100644
--- i/autoload/gitgutter/hunk.vim
+++ w/autoload/gitgutter/hunk.vim
@@ -504,7 +504,7 @@ function! s:populate_hunk_preview_window(header, body)
         call nvim_buf_add_highlight(winbufnr(s:winid), ns_id, group, region[0]-1, region[2]-1, region[3])
       endfor
 
-      call nvim_win_set_cursor(s:winid, [1,0])
+      noautocmd call nvim_win_set_cursor(s:winid, [1,0])
     endif
 
     if exists('*popup_create')
```

**Comment by airblade** [comment] 2020-08-06 14:51
Is the verbose output without `let g:loaded_matchparen=0` the same as the second block of output above?

**Comment by astier** [comment] 2020-08-06 17:02
`noautocmd call nvim_win_set_cursor(s:winid, [1,0])`

Doesn't help.

> Is the verbose output without let g:loaded_matchparen=0 the same as the second block of output above?

```
chdir(/home/aleks)
chdir(projects/dotfiles/dotfiles/nvim)
chdir(/home/aleks)
chdir(/home/aleks)
chdir(projects/dotfiles/dotfiles/nvim)
chdir(/home/aleks)
chdir(/home/aleks)
chdir(projects/dotfiles/dotfiles/nvim)
chdir(/home/aleks)
chdir(/home/aleks)
chdir(projects/dotfiles/dotfiles/nvim)
chdir(/home/aleks)
chdir(/home/aleks)
chdir(projects/dotfiles/dotfiles/nvim)
chdir(/home/aleks)
chdir(/home/aleks)
chdir(projects/dotfiles/dotfiles/nvim)
chdir(/home/aleks)
Executing FileType Autocommands for "*"
autocommand exe "set syntax=" . expand("<amatch>")
Executing Syntax Autocommands for "*"
autocommand call s:SynSet()
chdir(/home/aleks)
chdir(/home/aleks/.local/share/nvim/runtime/syntax)
chdir(/home/aleks)
line 24: sourcing "/home/aleks/.local/share/nvim/runtime/syntax/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/syntax/diff.vim
continuing in function <SNR>3_SynSet
Executing FileType Autocommands for "*"
autocommand call s:LoadFTPlugin()
chdir(/home/aleks)
chdir(/home/aleks/.local/share/nvim/runtime/ftplugin)
chdir(/home/aleks)
line 17: sourcing "/home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim"
finished sourcing /home/aleks/.local/share/nvim/runtime/ftplugin/diff.vim
continuing in function <SNR>6_LoadFTPlugin
Executing FileType Autocommands for "*"
autocommand call s:LoadIndent()
not found in 'runtimepath': "indent/diff.vim"
Executing BufFilePre Autocommands for "*"
autocommand GitGutterBufferDisable
Executing BufFilePost Autocommands for "*"
autocommand GitGutterBufferEnable
chdir(/home/aleks)
chdir(/home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter)
chdir(/home/aleks)
line 24: sourcing "/home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter/diff_highlight.vim"
finished sourcing /home/aleks/.local/share/nvim/plugins/vim-gitgutter/autoload/gitgutter/diff_highlight.vim
continuing in function gitgutter#hunk#preview[3]..<SNR>36_hunk_op[62]..<SNR>36_preview[6]..<SNR>36_populate_hunk_preview_window
```

**Comment by astier** [comment] 2020-08-06 17:04
This is totally weird. Thank you for your help so far. Just so you know. I don't expect from you at this point to do any further investigations.

**Comment by astier** [comment] 2020-08-06 17:43
It just became even weirder. Installed nvim v0.4.4 (issue still there). But I discovered that somehow `coc` makes the issue disappear.

```vim
set runtimepath=~/.local/share/nvim/plugins/vim-gitgutter/
set runtimepath+=~/.local/share/nvim/plugins/coc.nvim/
let g:loaded_matchparen=0
```

**Comment by airblade** [comment] 2020-08-07 07:59
Hmm, vim/vim#2053 sounds relevant.  Does this fix the problem?

```diff
diff --git i/plugin/gitgutter.vim w/plugin/gitgutter.vim
index 0576f87..afd835d 100644
--- i/plugin/gitgutter.vim
+++ w/plugin/gitgutter.vim
@@ -243,6 +243,8 @@ augroup gitgutter
 
   autocmd BufEnter * call s:on_bufenter()
 
+  autocmd CursorMoved * execute ''
+
   autocmd CursorHold,CursorHoldI * call gitgutter#process_buffer(bufnr(''), 0)
   if exists('*timer_start') && has('lambda')
     autocmd FileChangedShellPost * call timer_start(1, {-> gitgutter#process_buffer(bufnr(''), 1)})
```

**Comment by astier** [comment] 2020-08-07 09:44
It does fix the issue. Thank you very much. This was really a tricky one. Could you reproduce it on your machine?

**Closed** 2020-08-07 11:07 UTC

**Comment by airblade** [comment] 2020-08-07 11:10
Great news!  I was never able to reproduce it.  But I'm pleased we kept going and found a fix – thanks for your help.
