### ISSUE TITLE
Not being able to stage hunks partially as preview window is messed up

### ISSUE THREAD

**Issue by ravexina** [airblade/vim-gitgutter#809] opened 2021-11-12 08:02 UTC
> What is the latest commit SHA in your installed vim-gitgutter?

256702d (latest/master)

> What vim/nvim version are you on?

    $ vim --version
    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)
    Included patches: 1-2434

When I want to preview the hunks and stage them partially I'm not able to do so as the preview window looks kinda weird and after deleting the unwanted lines (or without removing anything) `GitGutterStageHunk` has no effect. 

It might be worth to mention that I'm also not able to close the preview window using (CTRL-W C) as I'm basically able to do with other windows.

What I have already tried? 
- Cleaning up my `vimrc` to make sure my config are not causing any trouble
- Removing all the other plugins to make sure there is no conflict
- Trying different terminals to see if it happens everywhere:
  - xterm
  - terminus
  - terminatior
  - xfce4-terminal

![2021-11-12-11:15:02-screenshot](https://user-images.githubusercontent.com/26504186/141429780-9212c9a5-e682-49d3-a644-765fac142b61.png)
![2021-11-12-11:15:27-screenshot](https://user-images.githubusercontent.com/26504186/141429793-502f63a1-d9d7-4414-9e7c-3e857866976c.png)
![2021-11-12-11:15:38-screenshot](https://user-images.githubusercontent.com/26504186/141429803-b8d3f702-e7d6-48b0-99a7-51f43314204f.png)

**Comment by ravexina** [comment] 2021-11-12 08:18
As I was sourcing multiple files in my `.vimrc` I missed disabling one of them while I was troubleshooting the problem. seems the issue was these two lines which I had for `YouCompleteMe`.

    set previewpopup=height:10,width:60,highlight:PMenuSbar
    set completepopup=height:15,width:60,border:off,highlight:PMenuSbar

**Comment by airblade** [comment] 2021-11-12 08:39
I'm glad you tracked down the problem!  Setting a vim option shouldn't break the plugin so I'm going to reopen this.

I implemented floating preview windows (see `:help g:gitgutter_preview_win_floating`) before `'previewpopup'` was added to vim and I never adjusted the code to allow for `'previewpopup'`'s behaviour.  They basically do the same thing so I'll see if I can simplify this.

However I think the main caveat of vim's floating windows applies to the popup preview window: it's read only.  So you can edit hunks in them.

**Comment by airblade** [comment] 2022-02-02 10:00
> I never adjusted the code to allow for 'previewpopup''s behaviour. 

That's not right: I adjusted the code in f2a825f and then in 7224d1d.

Anyway, the code works like this: if you have set `'previewpopup'` in your vimrc, it will show hunk previews in a floating window (using `popup_create()`).  Floating windows are not the same as Vim's popup preview windows so your actual `'previewpopup'` value is not used for the floating window.

https://github.com/airblade/vim-gitgutter/blob/e9871cf952bcedfde1fffbe89eb986150aab886e/plugin/gitgutter.vim#L28-L29

The only way I can reproduce your problem is to explicitly tell GitGutter not to use floating windows, i.e. to use a preview window, for hunk previews – and also set `'previewpopup'` so Vim uses its built-in popup preview window.  As you saw, the popup preview windows don't work well for this.

```viml
let g:gitgutter_preview_win_floating=0
set previewpopup=height:10,width:60
```

Personally I don't use floating hunk previews on Vim because you can't edit the hunk before staging it.  I stick to the normal, non-floating preview window.  Which, I have just realised, you would obtain with the config above that causes this problem.  I will fix this...

**Comment by airblade** [comment] 2022-02-02 10:03
With the above commit you can get a useful hunk preview (in an ordinary, non-floating preview window) which also using popup previews elsewhere:

```vim
let g:gitgutter_preview_win_floating=0
set previewpopup=height:10,width:60
```

**Comment by airblade** [comment] 2022-02-19 13:38
I'm assuming this is fixed now – let me know if not.

**Closed by airblade** 2022-02-19 13:38 UTC
