### ISSUE TITLE
E12: Command not allowed from exrc/vimrc in current dir or tag search

### ISSUE THREAD

**Issue by jparise** [airblade/vim-gitgutter#787] opened 2021-06-15 15:38 UTC
I run into an error (`E12: Command not allowed from exrc/vimrc in current dir or tag search)`) if I:

1. Open a file in a project that uses ctags.
2. Jump to a tag (`g]` or `g CTRK-]`) which results in a tag search list.
3. Choose one of the tag search results.

```
  # pri kind tag               file
  1 F   c    AccessToken       api/auth/tokens.py
               class AccessToken(ApiToken, ABC):
  2 F   c    AccessToken       thrift-types/auth/ttypes.py
               class AccessToken(TBase):
  3 F   c    AccessToken       third_party/yahoo/oauth.py
E435: Couldn't find tag, just guessing!
Press ENTER or type command to continue
Error detected while processing function <SNR>114_on_exit_vim[13]..1[5]..gitgutter#process_buffer[25]..function <SNR>114_on_exit_vim[13]..1[5]..gitgutter#process_buffer[19]..gitgutter#diff#run_diff[35]..<SNR>116_write_buffer:
line   32:
E12: Command not allowed from exrc/vimrc in current dir or tag search
Error detected while processing function <SNR>114_on_exit_vim[13]..1:
line    5:
E171: Missing :endif
Error detected while processing function <SNR>114_on_exit_vim:
line   13:
E171: Missing :endif
```

This appears to originate from the `writefile` call in `s:write_buffer()`:

https://github.com/airblade/vim-gitgutter/blob/0f98634b92da9a35580b618c11a6d2adc42d9f90/autoload/gitgutter/diff.vim#L407

I briefly thought about the best way to address this, but I realized I don't know enough about gitgutter's design to understand if this error should be fixed right here or at a higher level (for example, by not considering the tag search list a diff-able buffer in the first place).

> What is the latest commit SHA in your installed vim-gitgutter?

0f98634b92da9a35580b618c11a6d2adc42d9f90

> What vim/nvim version are you on?

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 15 2021 08:22:17)
macOS version - x86_64
Included patches: 1-3000
```

**Comment by airblade** [comment] 2021-06-16 10:54
I can't reproduce this with Vim 8.2.2566.

I wonder if the problem is triggered by the `E435`, which I can't reproduce either.  How do you get that?

**Comment by jparise** [comment] 2021-06-23 21:18
I'm still able to reproduce this, but I'll attempt to narrow it down further (including looking at the `E435`).

**Comment by jparise** [comment] 2021-06-29 17:27
This _does_ appear to be related to the [`E435`](https://vimhelp.org/tagsrch.txt.html#E435). I can't suggest how you can reproduce that particular error; it appears to be something related to both my source tree and `ctags` setup.

That being said, whenever `E435` occurs, I continue to get the gitgutter-related error dump above. If there are things I could try to narrow this down further, please let me know.

**Comment by airblade** [comment] 2021-06-30 11:51
You could turn on logging (`let g:gitgutter_log=1`; the log file will be in gitgutter's directory) and see which buffer it's processing when the error occurs, or if anything looks odd.  Feel free to upload it for me to take a look.

I doubt it's processing the tag search list because that's [not a file](https://github.com/airblade/vim-gitgutter/blob/0f98634b92da9a35580b618c11a6d2adc42d9f90/autoload/gitgutter/utility.vim#L55).

I was wondering about these lines:

```
E435: Couldn't find tag, just guessing!
Press ENTER or type command to continue
```

I presume the `E435` happens as part of step 2, i.e. it's more for information than an actual error.

Would you expect the press-enter prompt normally or is it caused by the E435?

**Comment by jparise** [comment] 2021-06-30 15:11
Nothing looks amiss in the log output. This is the only log even that occurs near the error:

```
 13.606850 BufEnter Autocommands for "*"..function <SNR>56_on_bufenter[22]..gitgutter#process_buffer[10]..<SNR>110_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 13.606850 [async] cd /mnt/api/auth && git  ls-files --error-unmatch --full-name -z -- tokens.py
```

Also, a little more hunting indicates that this has come up before: #374

I still haven't been able to narrow down _which_ command is actually causing this error. It feels like something related to the async code which either (a) doesn't like the delay caused by the `enter` prompt or (b) doesn't like being run while the tagsearch buffer is active.

**Comment by airblade** [comment] 2021-07-01 11:00
Hmm, this would be easier if I could reproduce the E435 ;)

When does the hit-enter prompt appear?  Is it with the E435 or a bit later?

And in your example, was the tag you chose pointing to `tokens.py`?

**Comment by jparise** [comment] 2021-07-01 16:34
> Hmm, this would be easier if I could reproduce the E435 ;)

And now I can't either. I rebuilt my tags file, which appears to have addressed the E435 issue (and therefore the issue I was seeing with gitgutter). Unfortunately, I no longer have a environment in which I can help track down the async conflict.

> When does the hit-enter prompt appear? Is it with the E435 or a bit later?

It came just after the E435.

> And in your example, was the tag you chose pointing to `tokens.py`?

Yes, and I had added some message logging throughout gitgutter to verify that it was only working with buffers related to that file.

**Comment by airblade** [comment] 2021-07-02 08:33
I looked at the [code that generates the E435](https://github.com/vim/vim/blob/4781d6fd8670af415c3b78f00d70036af85bd286/src/tag.c#L3604) but I'm not familiar enough with Vim's internals to see any problems.

I presume this is some kind of Vim bug where the hit-enter prompt interrupts the async callback – but I'm not sure how to test this hypothesis.

I'm inclined to close the issue because it's rare and I don't know how to address it anyway.

**Comment by jparise** [comment] 2021-07-03 22:25
I don't object, although it seems like someone will eventually run into this again at some point.

Do you have enough detail to file an upstream vim issue?

**Comment by airblade** [comment] 2021-07-05 08:37
> Do you have enough detail to file an upstream vim issue?

Not really: I'd prefer to be able to reproduce the problem.  But I opened an issue anyway.

**Comment by airblade** [comment] 2021-07-07 10:55
Closing because this is addressed in https://github.com/vim/vim/issues/8511.

**Closed by airblade** 2021-07-07 10:55 UTC
