### ISSUE TITLE
let g:gitgutter_diff_base = 'HEAD' not working

### ISSUE THREAD

**Issue by pkalever** [airblade/vim-gitgutter#339] opened 2016-05-18 12:15 UTC
I really like the Idea!
Thumps Up for this :+1: 
I have just cloned it, and it works for me but I have noticed one issue on the latest code.
Not sure if this is broken on latest master. I don't think "let g:gitgutter_diff_base = 'HEAD'" is working, at least for me. 

using VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 8 2016 14:13:25) 
on fedora 23

**Comment by airblade** [comment] 2016-05-18 12:17
Please post steps to reproduce the problem.

**Comment by airblade** [comment] 2016-06-16 09:03
Closing because I can't reproduce this.

**Closed by airblade** 2016-06-16 09:03 UTC
