### ISSUE TITLE
Errors involving `gitgutter#utilitiy#set_repo_path` on opening buffer pointing to a file in repo

### ISSUE THREAD

**Issue by HarrisonB** [airblade/vim-gitgutter#625] opened 2019-06-05 17:05 UTC
```
Error detected while processing function <SNR>60_on_bufenter[5]..gitgutter#process_buffer[12]..<SNR>191_setup_path:
line    7:
E118: Too many arguments for function: gitgutter#utility#set_repo_path
E15: Invalid expression: gitgutter#utility#set_repo_path(a:bufnr, a:continuation)
```

> What is the latest commit SHA in your installed vim-gitgutter?

07b60b5

> What vim/nvim version are you on?

NVIM v0.3.5

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

I get an error akin to `key not present in Dictionary`

**Comment by airblade** [comment] 2019-06-06 10:52
Hmm, I can't reproduce this with NVIM 0.3.7.

The `process_buffer()` function [calls](https://github.com/airblade/vim-gitgutter/blob/07b60b584ea603693d24a72207de58a446e0b5ec/autoload/gitgutter.vim#L35) `s:setup_path()` with a buffer number and a funcref.  `s:setup_path()` then [calls](https://github.com/airblade/vim-gitgutter/blob/07b60b584ea603693d24a72207de58a446e0b5ec/autoload/gitgutter.vim#L160) `set_repo_path()` with those same arguments; `set_repo_path()` takes [two arguments](https://github.com/airblade/vim-gitgutter/blob/07b60b584ea603693d24a72207de58a446e0b5ec/autoload/gitgutter/utility.vim#L141).  I can't think why this could misbehave.

The only tricky part is [creating the funcref](https://github.com/airblade/vim-gitgutter/blob/07b60b584ea603693d24a72207de58a446e0b5ec/autoload/gitgutter.vim#L30-L34), but that's already happened by the time the above code is called.

Would you mind adding this line and seeing what's in `:messages` after the error occurs?

```diff
diff --git i/autoload/gitgutter.vim w/autoload/gitgutter.vim
index cc6f7cf..b51273b 100644
--- i/autoload/gitgutter.vim
+++ w/autoload/gitgutter.vim
@@ -157,6 +157,7 @@ function! s:setup_path(bufnr, continuation)
     return
   endif
 
+  echom string(a:continuation)
   return gitgutter#utility#set_repo_path(a:bufnr, a:continuation)
 endfunction
```

Also, does it work if you roll back vim-gitgutter to 50932df5?

**Comment by HarrisonB** [comment] 2019-06-07 20:06
Thanks for responding so quickly!

> Would you mind adding this line and seeing what's in `:messages` after the error occurs?
> 
> ```diff
> diff --git i/autoload/gitgutter.vim w/autoload/gitgutter.vim
> index cc6f7cf..b51273b 100644
> --- i/autoload/gitgutter.vim
> +++ w/autoload/gitgutter.vim
> @@ -157,6 +157,7 @@ function! s:setup_path(bufnr, continuation)
>      return
>    endif
>  
> +  echom string(a:continuation)
>    return gitgutter#utility#set_repo_path(a:bufnr, a:continuation)
>  endfunction
> ```

I get `function('gitgutter#process_buffer', [1, 0])`

> 
> Also, does it work if you roll back vim-gitgutter to [50932df](https://github.com/airblade/vim-gitgutter/commit/50932df59a11775a520eb1a1b427244bad47d6e4)?

It does!

**Comment by airblade** [comment] 2019-06-10 11:00
That all looks good.

I'm not sure why you're getting that error message.

Do you happen to know how to install old versions of neovim on macOS via Homebrew?

**Comment by HarrisonB** [comment] 2019-06-10 16:44
I don't know if there is one (see https://github.com/Homebrew/brew/issues/6065). You may have to build from source.

I will note that upgrading to 0.3.7 seemed to have resolved my issues. Will update if I run into other problems.

**Comment by airblade** [comment] 2019-06-10 17:57
I can't reproduce this in 0.3.7.

Do you still get this error when vim-gitgutter is the only plugin installed?

**Comment by airblade** [comment] 2019-07-26 09:33
Closing because this has gone quiet but let me know if you're still having trouble.

**Closed by airblade** 2019-07-26 09:33 UTC
