### ISSUE TITLE
Discarding a file with fugitive doesn't update signs

### ISSUE THREAD

**Issue by h0adp0re** [airblade/vim-gitgutter#814] opened 2022-01-28 16:57 UTC
> What is the latest commit SHA in your installed vim-gitgutter?
`256702dd1432894b3607d3de6cd660863b331818`

> What vim/nvim version are you on?
`NVIM v0.6.1`

It seems to me when I discard a file under the cursor with fugitive via its keybind `X`, gitgutter doesn't update the signs...

I've tried to add an `autocmd` that is already probably present in this codebase. It doesn't work.
```vim
autocmd User FugitiveChanged call gitgutter#all(1)
```

**Comment by airblade** [comment] 2022-01-29 14:43
The problem is the order of events.

Fugitive discards the change, then updates its status buffer, then causes your file to be reloaded with `checktime`.

https://github.com/tpope/vim-fugitive/blob/59529a2c3634dc1cb3956c4faaf824f5c4dd7be1/autoload/fugitive.vim#L4948

The `FugitiveChanged` (and `FugitiveIndex` events) are fired before `checktime` is executed.  But it's only when `checktime` executes that GitGutter sees the file has changed and updates the signs.

You can test this by removing the `checktime` from Fugitive (in the line linked above), then manually executing `checktime` in your buffer.  GitGutter updates the signs as expected.

One workaround is to set `let g:gitgutter_terminal_reports_focus=0`.  This means that when you enter a buffer GitGutter will always update the signs; normally it only it updates the signs when it knows the buffer has changed.

In the meantime I'm working on a proper solution.

**Comment by airblade** [comment] 2022-01-29 15:16
This should be fixed now.  Please try it out and let me know how you get on.

**Comment by h0adp0re** [comment] 2022-01-29 21:59
It works! Thank you very much!

**Closed** 2022-01-29 21:59 UTC
