### ISSUE TITLE
Invalid expression: job_info

### ISSUE THREAD

**Issue by albasili** [airblade/vim-gitgutter#790] opened 2021-07-06 09:23 UTC
> What is the latest commit SHA in your installed vim-gitgutter?
0f98634b92da9a35580b618c11a6d2adc42d9f90

> What vim/nvim version are you on?
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 18 2016 14:42:40)

This is what I have when I enable the plugin.
```
E916: not a valid job
E121: Undefined variable: process
E15: Invalid expression: job_info(a:job).process
Error detected while processing function <SNR>152_on_exit_vim:
```

The error happens every refresh cycle. I'm on a new server configuration in a new company so I believe there's some dependency that is breaking the plugin. The distro is a CentOS, but I'm not sure to which extent it matters:
```
[basili@fe-basili ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
```

**Comment by airblade** [comment] 2021-07-06 10:37
I have never seen that before and I don't know what might be causing it.  Vim should be self-contained so the OS shouldn't matter.

Does the output of `vim --version` include `+channel` and `+job`?

It sounds a bit like https://github.com/vim/vim/issues/1242.  Can you reproduce your error with the reproduction-steps given in that issue?

**Comment by airblade** [comment] 2021-09-29 08:18
Closing because this has gone quiet but happy to reopen if you're still having problems.

**Closed by airblade** 2021-09-29 08:18 UTC
