### ISSUE TITLE
Unwanted string `syntax=` appears when in insert mode.

### ISSUE THREAD

**Issue by mattfinnell** [airblade/vim-gitgutter#430] opened 2017-07-26 02:31 UTC
![vimsyntaxerror](https://user-images.githubusercontent.com/4606321/28601623-28a5d034-716e-11e7-96eb-d12eabbf1abf.png)

Title should state most. This non-deterministically occurs when entering insert mode.

**Comment by airblade** [comment] 2017-07-26 07:50
How odd.  Are you sure this is due to vim-gitgutter?  I can't think of anything that would cause this, and `syntax` doesn't appear in the code anywhere.

**Comment by airblade** [comment] 2017-09-01 13:48
I'm confident this isn't caused by vim-gitgutter so I'm closing it.  Happy to reopen if you can show otherwise.

**Closed by airblade** 2017-09-01 13:48 UTC

**Comment by mattfinnell** [comment] 2017-10-27 09:09
So I recently rebuilt my vim configuration and reincorporated `vim-gitgutter`. I haven't come across any problems with the stray string and am now loving your creation!

For some more slightly more useful information. I swapped out `pathogen` for `plug`. I think due to `plug`'s lazy evaluation, all the plugins are now being loaded in a nice order in a minimal manner. Where pathogen might have been loading all plugins at once without planning load-order.

**Comment by airblade** [comment] 2017-10-27 09:38
Thanks for the extra info, and glad to hear it's working!
