### ISSUE TITLE
Sign updates conflict with deoplete.nvim

### ISSUE THREAD

**Issue by mroavi** [airblade/vim-gitgutter#719] opened 2020-07-01 11:31 UTC
> What is the latest commit SHA in your installed vim-gitgutter?
c27bfab8c51e77419ee0c4a9c4e3ba359dbc2ad4

> What vim/nvim version are you on?
NVIM v0.5.0-577-g48ac77a14

The gitgutter signs are not being updated after enabling deoplete with:
```vim
let g:deoplete#enable_at_startup = 1
```
If, however, I switch focus to another tmux pane and back, then the signs get updated.

This problem does not occur if deoplete is not enabled. I have `updatetime` set to `100`.

Here is a gif demonstrating the above:

![git-gutter-bug](https://user-images.githubusercontent.com/19517248/86239145-0bc6e600-bb9f-11ea-8288-4d29840b0a9e.gif)

**Comment by airblade** [comment] 2020-07-03 09:18
I tried to install deoplete but it requires Python 3, and then other Python stuff, and I don't particularly want to install any of that.  So I wasn't able to reproduce the problem.

With deoplete enabled at startup, once you open nvim and modify something, but before you change to another tmux pane, what does `:echo b:gitgutter` produce?

**Comment by mroavi** [comment] 2020-07-03 09:54
```vim
:echo b:gitgutter

{'hunks': [], 'path': 'nvim/.config/nvim/init.vim', 'summary': [0, 0, 0], 'tick': 2}
```

By the way, I verified that I have the same problem without starting tmux.

**Comment by mroavi** [comment] 2020-07-07 11:22
Apparently it is a neovim bug: https://github.com/neovim/neovim/issues/12587

**Comment by airblade** [comment] 2020-07-07 11:34
That's a relief (for me) – I didn't know what the problem was ;)

I'll close this because it's not a vim-gitgutter bug, but please feel free to comment if you find a way vim-gitgutter could work around it.

**Closed by airblade** 2020-07-07 11:34 UTC

**Comment by antoinemadec** [comment] 2020-07-13 01:40
@airblade , @mroavi , could you please try the following plugin and tell me if it fixed your issue?
https://github.com/antoinemadec/FixCursorHold.nvim

**Comment by airblade** [comment] 2020-07-14 09:00
@antoinemadec Thanks, but I wasn't able to reproduce the original issue (due to not being able to install deoplete in the time available).

**Comment by mroavi** [comment] 2020-07-14 14:13
> @airblade , @mroavi , could you please try the following plugin and tell me if it fixed your issue?
> https://github.com/antoinemadec/FixCursorHold.nvim

See: https://github.com/Shougo/deoplete.nvim/issues/1112#issuecomment-657723927
