### ISSUE TITLE
vim-gitgutter doesn't work with csh

### ISSUE THREAD

**Issue by riesebie** [airblade/vim-gitgutter#365] opened 2016-08-05 12:44 UTC
Error detected while processing function gitgutter#utility#git_supports_command_line_config_override[1]..gitgutter#utility#git_version:
line    1:
E484: Can't open file /tmp/v0mXMKI/2

csh --version
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-amd-FreeBSD) options wide,nls,dl,al,kan,sm,rh,color,filec

Runing zsh works fine.

On commandline git --version tells:
git version 2.9.2

This is FreeBSD 10.3

**Comment by airblade** [comment] 2016-08-08 10:12
What happens when you do this under csh?

```
:echo system('git --version')
```

**Comment by riesebie** [comment] 2016-08-13 10:44
* Andy Stewart <notifications@github.com> [2016-08-08 03:12 -0700]:

> What happens when you do this under csh?
> 
> ```
> :echo system('git --version')

git version 2.9.2

-- 
   Elimar

**Comment by hholst80** [comment] 2016-08-14 18:29
I was just going to report the same problem. Good catch @riesebie I did not think of checking my shell!

**Comment by riesebie** [comment] 2016-08-16 18:14
> if $SHELL =~ "/bin/csh"
      set shell=/bin/zsh
   endif

helped. C-Shell is supposed to be a NON-POSIX shell and therefor isn't supported?

**Comment by airblade** [comment] 2016-08-17 08:04
The stacktrace from your error message points to [this line](https://github.com/airblade/vim-gitgutter/blob/26c6b549f287b8ae348eda083e7c77f79f4de28b/autoload/gitgutter/utility.vim#L172), which calls `system('git --version')`.

I don't understand why it works when you execute that by hand, on Vim's command line, but not when executed by vim-gitgutter.

These days Vim is supposed to support non-POSIX shells.  Anyway, vim-gitgutter switches to `/bin/sh` before running any external commands using pipes and/or redirection.

What shell does `/bin/sh` resolve to on your system?

**Comment by riesebie** [comment] 2016-08-17 09:43
* Andy Stewart <notifications@github.com> [2016-08-17 01:04 -0700]:

> The stacktrace from your error message points to [this line](https://github.com/airblade/vim-gitgutter/blob/26c6b549f287b8ae348eda083e7c77f79f4de28b/autoload/gitgutter/utility.vim#L172), which calls `system('git --version')`.
> 
> I don't understand why it works when you execute that by hand, on Vim's command line, but not when executed by vim-gitgutter.
> 
> These days Vim is supposed to support non-POSIX shells.  Anyway, vim-gitgutter switches to `/bin/sh` before running any external commands using pipes and/or redirection.
> 
> What shell does `/bin/sh` resolve to on your system?

It represents the "Bourne Shell"
http://www.freebsd.org/cgi/man.cgi?sh(1)

**Comment by serpent7776** [comment] 2016-08-31 20:29
I'm also experiencing this problem. There must be something wrong with shell settings, because even simple `:echo system('echo 1')` fails with `E484: Can't open file`.
Last working version is at 1937f064983be3a68418c4edbf5317226e85ae4d. Next commit breaks (because tries to use /bin/bash, which doesn't exist), but working fine if I edit `autoload/gitgutter/utility.vim` to use `/bin/tcsh` instead of `/bin/bash`. Changing `/bin/bash` to `/bin/sh` does not fix the issue.
I think there is some issue when running `/bin/sh` on FreeBSD.

**Comment by airblade** [comment] 2016-09-05 16:37
> There must be something wrong with shell settings, because even simple `:echo system('echo 1')` fails with `E484: Can't open file`.

Well if that doesn't work, this plugin doesn't have a chance ;)

A quick way to look at the shell settings is to do `:GitGutterDebug`.

**Comment by serpent7776** [comment] 2016-09-05 20:35
> There must be something wrong with shell settings, because even simple :echo system('echo 1') fails with E484: Can't open file.

I rechecked this and `:echo system()` doesn't work only after gitgutter fails with `E484: Can't open file`. If I open vim with empty buffer it works as expected. I think it is because gitgutter don't restore shell settings after that error and leave vim with `shell` set to `/bin/sh`.

`:GitGutterDebug` tells me this on last working version:
[gitgutter-debug-ok.log](https://gist.github.com/serpent7776/587f34d3398412e47541546c457864c1)
and for not working version after `E484: Can't open file` occurs:
[gitgutter-debug-not-ok.log](https://gist.github.com/serpent7776/9f6006216168a6ef4d70a9bfefc0fce1)
and I get a bunch of `E484: Can't open file` errors

For both current and last working version when I open vim with empty buffer and do `:set shell=/bin/sh` I get `E484: Can't open file` for `:echo system('echo 1')`. This puzzles me.

**Comment by serpent7776** [comment] 2016-09-05 20:46
I just found that vim-plug seem to had similar issue [here](https://github.com/junegunn/vim-plug/issues/159).
The fix is to do `set shellredir=>%s\ 2>&1`, because `>&` redirection is bashism and is not recognized by POSIX shell (/bin/sh).
I can confirm that when I do `:set shell=/bin/sh` and set `shellredir` to above value I can successfully execute `:echo system('echo 1')`.
One possible drawback is that this includes stderr as well as stdout - I don't know is this an isue for gitgutter.

**Comment by airblade** [comment] 2016-09-06 09:39
@serpent7776 I think you've nailed it.

@riesebie @hholst80 @serpent7776 Please could you try 43e7c1f and make sure it works for you?

**Comment by serpent7776** [comment] 2016-09-06 19:54
Works fine for me.

**Comment by airblade** [comment] 2016-09-13 14:57
Thanks for letting me know @serpent7776.  I'm going to assume this solves the problem for everyone and close the issue.

Let me know if you still have problems.

**Closed by airblade** 2016-09-13 14:57 UTC

**Comment by riesebie** [comment] 2016-09-13 15:20
Latest versions works fine. Thanks @serpent7776 @airblade for cooperation
