### ISSUE TITLE
git_supports_command_line_config_override..gitgutter#utility#git_version

### ISSUE THREAD

**Issue by sivaswami** [airblade/vim-gitgutter#368] opened 2016-08-26 05:22 UTC
I used vimrc from shared drive across multiple machines
In one machine I get the below error. In one of the threads I learnt that this could be due to unavailability of Git command in the machine. Is there any way I can check if Git is present/available in that machine and disable the error message automatically?

Error detected while processing function gitgutter#utility#git_supports_command_line_config_override..gitgutter#utility#git_version:
line    1:
E484: Can't open file /tmp/v214504/7

**Comment by airblade** [comment] 2016-09-05 16:21
[These lines](https://github.com/airblade/vim-gitgutter/blob/26c6b549f287b8ae348eda083e7c77f79f4de28b/plugin/gitgutter.vim#L56-L58) check whether git exists on the machine.  Does your installed version of the plugin contain those lines?

**Comment by airblade** [comment] 2016-09-14 15:25
Any updates?

**Comment by sivaswami** [comment] 2016-09-14 21:07
I see 2 gitgutter.vim files. 
./plugin/gitgutter.vim
./autoload/gitgutter.vim

In plugin gitgutter.vim, I see the line you mentioned. but not in autoload folder

**Comment by airblade** [comment] 2016-09-16 13:28
I've just realised there's another possible cause of this error.  On the problematic machine, what does `which sh` give?

**Comment by HerrmannM** [comment] 2016-10-12 10:41
Hi there,

Same kind of error here :` gitgutter#utility#git_supports_command_line_config_override`
However, it comes with a E688 error, 'more targets than list items'.

`which sh` gives me `/usr/bin/sh`

Note that this error just appears for me...

**Comment by yereby** [comment] 2016-11-16 16:56
Hello,
I have the same error plus `Error detected while processing function gitgutter#all line 4: endif missing`

This only on ubuntu and gvim, not on ubuntu and vim

**Comment by twmht** [comment] 2016-12-03 09:56
I have the same errors in windows gvim.

**Comment by bkaradzic** [comment] 2016-12-04 07:06
I just ran into this issue on Windows... Version string is "git version 2.11.0.windows.1", if I change this line:
https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/utility.vim#L183 just to parse '2.11.0', everything is fine...

**Comment by twmht** [comment] 2016-12-05 04:07
@bkaradzic 

Can you show what you change?

**Comment by bkaradzic** [comment] 2016-12-05 04:50
I just hacked version value until there is better fix (I'm not familiar with vim script):

```
function! gitgutter#utility#git_supports_command_line_config_override() abort
- let [major, minor, patch; _] = split(gitgutter#utility#git_version(), '\.')
+ let [major, minor, patch; _] = split('2.11.0', '\.')
  return major > 1 || (major == 1 && minor > 7) || (minor == 7 && patch > 1)
endfunction
```

**Comment by twmht** [comment] 2016-12-05 06:28
@bkaradzic 

it works! thank you.

**Comment by airblade** [comment] 2016-12-05 16:20
@bkaradzic Thanks for posting that.

The strange is this works for me:

```viml
:echo split(matchstr('git version 2.11.0.windows.1', '[0-9.]\+'), '\.')
```

It produces `['2', '11', '0']`.

Does this not work for you?

**Comment by twmht** [comment] 2016-12-06 02:36
@airblade  and @bkaradzic 

I try bkaradzic's workaround and `GitGutterEnable` works without any exception.

However, I can not see any git sign showing in windows gvim.

By the way, my windows gvim is built with cygwin.

**Comment by airblade** [comment] 2016-12-06 09:51
@twmht I don't have access to a Windows box so I can't reproduce your problem.

What does `:GitGutterDebug` produce?

**Comment by airblade** [comment] 2016-12-06 09:53
@twmht Also, does `:echo system('git --version')` work for you?

**Comment by twmht** [comment] 2016-12-06 11:27
@airblade 

`echo system('git --version')` shows `git version 2.10.2.windows.1`

**Comment by twmht** [comment] 2016-12-06 11:32
@airblade 

`:echo system('git --version')` shows `Can not open file C:/Users/tumh/AppData/Local/Temp/VIo2396.tmp`

![image](https://cloud.githubusercontent.com/assets/1567200/20924091/a76fe9e8-bbea-11e6-8ad2-1c01f902907b.png)

**Comment by twmht** [comment] 2016-12-06 11:34
`:GitGutterDebug ` shows

![image](https://cloud.githubusercontent.com/assets/1567200/20924137/eca0df40-bbea-11e6-9606-b2844d99cf1d.png)

**Comment by twmht** [comment] 2016-12-06 11:39
And the command `:echo split(matchstr('git version 2.11.0.windows.1', '[0-9.]\+'), '\.')` shows `['2', '10', '2']`

**Comment by airblade** [comment] 2016-12-06 11:45
The problem is that your Vim can't run the external commands that the plugin wants to, probably because the shell is set wrongly for you.

Please can you tell me what `:verbose set shell? shellcmdflag? shellxquote?` produces?

**Comment by twmht** [comment] 2016-12-06 11:47
@airblade 

`:verbose set shell?` shows 

![image](https://cloud.githubusercontent.com/assets/1567200/20924533/ca659f0e-bbec-11e6-8ed2-a4adf83225cd.png)

**Comment by twmht** [comment] 2016-12-06 11:48
and `shellcndflag=-c`  , shellxquote="`

**Comment by twmht** [comment] 2016-12-06 11:53
oh...

It works when running from windows cmd, instead of git bash shell. 

However, I need to explicitly call `:GitgutterEnable`  to see the signs.

**Comment by airblade** [comment] 2016-12-06 12:02
I suspect that Vim is seeing your `shell` and thinking it's in a Unix environment, and escaping the external command accordingly.  But in fact it's on Windows and the escaping is wrong.

A similar thing came up in #285 and #206.

Since it works when run from Windows cmd, perhaps you could `set shell=C:\WINDOWS\system32\cmd.exe` in your vimrc?

I'm not sure why you need to call `:GitGutterEnable` to see the signs.  You could try `let g:gitgutter_log = 1` and see if there's anything odd in the log file (which will be in the directory where gitgutter is installed).

**Comment by twmht** [comment] 2016-12-06 14:25
well, `:GitGutterDebug` from windows cmd also shows 

![image](https://cloud.githubusercontent.com/assets/1567200/20928910/dfa07a54-bc02-11e6-8978-b7727665766e.png)

But when I call `:GitGutterEnable`, anything works fine.

**Comment by baskus** [comment] 2017-03-01 11:48
I just hit this after updating git on windows to
```
~  $ git version
git version 2.12.0.windows.1
```

**Comment by airblade** [comment] 2017-03-01 11:54
@baskus What version of gitgutter are you using?  I had hoped this was fixed by ce8b5a408.

**Comment by baskus** [comment] 2017-03-01 12:12
I was using the ancient version
```
commit b5f23e986747a6f4b1dc1196d2a5bd3dc7c8c2b6
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Mon Jun 27 10:55:26 2016 +0100
```
and kept getting a popup that said
```
vim-gitgutter: cannot find git. Please set g:gitgutter_git_executable.
```
on startup. After that I got the error
```
Error detected while processing function gitgutter#utility#git_supports_command_line_config
```
while editing on every save and ever now and then while scrolling around.

However, since updating, I only get the popup on startup and no longer the error while editing. I cannot run git using `:!git` but a console opened from exporer.exe's ctrl-right click menu can find git. Do I have to set `g:gitgutter_git_executable` in newer versions? Should that not be autodetected when it works in cmd? Why does it not work in vim using `:!git`?

Sorry for not updating before I posted here, I just assumed it wasn't fixed since the issue was still open.

**Comment by airblade** [comment] 2017-03-01 12:18
> However, since updating, I only get the popup on startup and no longer the error while editing. I cannot run git using :!git but a console opened from exporer.exe's ctrl-right click menu can find git. Do I have to set g:gitgutter_git_executable in newer versions? Should that not be autodetected when it works in cmd? Why does it not work in vim using :!git?

It's all to do with the PATH made available to vim, and whether git is on that path.  In turn that depends on how you installed git.

I don't have access to a Windows box (and I'm not familiar with Windows) so I can't make much headway with this kind of problem.  Does it work if you do set `g:gitgutter_git_executable`?

**Comment by airblade** [comment] 2017-03-01 12:19
In the meantime I'm going to close this issue because ce8b5a4 resolved it.

**Closed by airblade** 2017-03-01 12:19 UTC

**Comment by baskus** [comment] 2017-03-16 10:00
After a reboot it no longer complains. :) I think something got messed up when I upgraded git for windows without rebooting. Thanks for all the help. :)

**Comment by kingdonb** [comment] 2017-07-31 14:32
I hit this issue after uninstalling Xcode.  All of a sudden I was getting this error spewed in vim errors every time I launched vim.  It turned out that not only was gitgutter in vim broken, but so was Git as a whole – impossible to commit, view status, or change branches.

The solution for me was to `sudo xcode-select -r` to prevent whatever xcode wrapper was wrapping the git binary, from doing... whatever it was doing.

**Comment by airblade** [comment] 2017-07-31 15:28
@kingdonb Good to know, thanks!

**Comment by thumbcore** [comment] 2018-12-21 17:45
Another data point: I added `set shell=C:/Windows/system32/cmd.exe` in my `_vimrc` and the issue went away for me. Thanks!

- Windows 7 (x64)
- gVIM 8.0.586
- git version 2.20.1.windows.1

**Comment by LegionNexus** [comment] 2024-04-17 15:35
[This is how I fixed it](https://vi.stackexchange.com/a/44648/51023)
My env: `Neovim` inside `Msys2`, on `Windows 10`
`vim.opt.shell = "bash"
vim.opt.shellcmdflag = "-c"
vim.opt.shellxquote = '""'
vim.opt.shellslash = true`
