### ISSUE TITLE
Slow switching between changeset

### ISSUE THREAD

**Issue by iamkarlson** [airblade/vim-gitgutter#378] opened 2016-10-16 06:17 UTC
I have two followed plugins in vimrc:
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

When I go to diff, navigation by ]c or [c become extremely slow, around 1-2 second. When I disable plugin always came back to normal speed.

**Comment by airblade** [comment] 2016-10-16 16:33
Can you please profile what happens when you press ]c or [c and post the result?  (See `:h profile`.)

**Comment by iamkarlson** [comment] 2016-10-16 18:25
I made that before creating issue. Could you check, is it enough? 
[profile.txt](https://github.com/airblade/vim-gitgutter/files/532021/profile.txt)

**Comment by airblade** [comment] 2016-10-17 08:29
That profile only contains information about fugitive; and I can't see anything slow at all.

When you use ]c and [c in a diff, vim-gitgutter [passes the ]c or [c straight through](https://github.com/airblade/vim-gitgutter/blob/297678a08da0c2d1819d6cb98504f8a843395456/plugin/gitgutter.vim#L144-L145).

In you original description of the issue, you said normal speed comes back when you disable the plugin.  Which plugin did you mean: fugitive or gitgutter?

**Comment by iamkarlson** [comment] 2016-10-17 10:03
I'm not sure, but [this function](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/hunk.vim#L40)
 may be cause of such behavior

**Comment by iamkarlson** [comment] 2016-10-17 10:04
If I have too many hunks it can take long time to go through

**Comment by airblade** [comment] 2016-10-17 17:05
I can't do anything without a profile.  The one above doesn't have any gitgutter functions in it.

**Comment by iamkarlson** [comment] 2016-10-24 10:52
I ran:

profile func *
profile file *

]c
[c

And then I got next profile log: 
[gitgutter-vim.profile](https://github.com/airblade/vim-gitgutter/files/547536/gitgutter-vim.profile.txt)

**Comment by iamkarlson** [comment] 2016-10-24 10:53
And I disabled figitive before running that

**Comment by airblade** [comment] 2016-10-27 14:23
Your profile doesn't contain any information about gitgutter.  Please could you try [like this](https://github.com/airblade/vim-gitgutter/wiki/How-to-profile-vim-gitgutter)?

**Comment by airblade** [comment] 2016-12-06 09:47
I'm closing this because I can't reproduce the problem and I can't begin to diagnose the problem without a profile.

**Closed by airblade** 2016-12-06 09:47 UTC

**Comment by iamkarlson** [comment] 2017-02-26 07:37
I found finally. Vim wait for a second if only one char typed. That's why I saw lags. Just switched to double ] as mapping and everything works fine

**Comment by airblade** [comment] 2017-02-28 14:33
Glad you solved the problem.

Vim's documentation for `timeout`, `ttimeout`, `timeoutlen` and `ttimeoutlen` might be relevant.
