### ISSUE TITLE
Gitgutter throws error when switching desktops on Mac in Neovim terminal

### ISSUE THREAD

**Issue by msmith491** [airblade/vim-gitgutter#463] opened 2018-02-09 17:19 UTC
# Environment
## OS
```
Mac OSX High Sierra
Version 10.13.1 (17B1003)
Terminal: ITerm2 Build 3.1.3.beta.1
Shell: zsh 5.2 (x86_64-apple-darwin15.0.0)
Git: git version 2.11.0
```
## Neovim
```
vi --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/config -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/include
Compiled by brew@HighSierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

Run :checkhealth for more info
```
## Gitgutter (installed via Vim-Plug)
```
git log -n 1 | cat
commit 932ffaca092cca246b82c33e23d2d3a05e192e08
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Mon Jan 29 15:30:25 2018 +0000

    Ensure we write correct buffer.

    Fixes #454.
```
## Gitgutter Settings
```
" Shows git file changes to the left of line numbers
Plug 'airblade/vim-gitgutter'
set signcolumn=yes
let g:gitgutter_max_signs = 1000
```

## Reproduction
1. Open five buffers, (3 text files, two terminals)
2. Make changes in the text files so gitgutter shows changes in the sidebar
3. Run a few commands in both terminals (I use zsh, not sure if it matters)
4a. (Optional Trigger) Make a git commit and use a nested Vim editor
4b. Switch desktops away from Fullscreen Iterm2 (I use Option+Left) while cursor is on one of the terminal buffers (doesn't matter if Normal or Terminal mode, just needs to be on the buffer), then switch back (Option+Right)
5.  The below error triggers and causes the terminal buffer to switch to one of the 3 text buffers.  Terminal buffer is deleted by Neovim.  This can be repeatedly triggered by opening a new terminal buffer, moving the cursor to it and switching desktops.

## Error
```
Error detected while processing function gitgutter#all[4]..gitgutter#process_buffer[10]..gitgutter#diff#run_diff:
line   38:
E86: Buffer 17 does not exist
Error detected while processing function gitgutter#all:
line    4:
E171: Missing :endif
"Makefile" [Modified] 52 lines --1%--
E86: Buffer 17 does not exist
Error detected while processing function gitgutter#all[4]..gitgutter#process_buffer[10]..gitgutter#diff#run_diff:
line   38:
E86: Buffer 97 does not exist
Error detected while processing function gitgutter#all:
line    4:
E171: Missing :endif
```

**Comment by juancampa** [comment] 2018-02-10 00:06
I'm getting what looks like the same issue. This is the error I get in `:mess`

```
Error detected while processing function gitgutter#all[4]..gitgutter#process_buffer[10]..gitgutter#diff#run_diff:
line   36:
E37: No write since last change (add ! to override)
Error detected while processing function gitgutter#all:
line    4:
E171: Missing :endif
```
It happens when I switch from another tmux pane back into the pane containing nvim

**Comment by airblade** [comment] 2018-02-12 15:29
I can reproduce more simply:

1. Open an unmodified file from a git repo.
2. Split-open a new buffer and start a terminal with `:terminal`.
3. Focus a different application.
4. Focus the neovim window.
  - This triggers the error.

This is what happens in step 4:

- The `FocusGained` event runs `gitgutter#all(1)`.
- This loops through the visible windows and runs `gitgutter_process(bufnr, 1)` on each.
- As part of git-diffing the file from step 1, the plugin needs to write the file to a temporary file.  I can't find a way to do this from another buffer, so [instead the plugin](https://github.com/airblade/vim-gitgutter/blob/5bfe5b92099e0d332a7ca26c0263fab509ee9617/autoload/gitgutter/diff.vim#L295-L311):
  - switches to the file's buffer
  - saves it to a temp file
  - switches back to the original buffer, i.e. the terminal.  However neovim closed the terminal buffer when the plugin switched to the file's buffer, so there's no buffer to return to.

The correct solution is to find a way to write a buffer (which isn't the current buffer) to a temporary file without leaving the current buffer.

In the meantime, it would be good to stop neovim closing the terminal buffer when we change to a different buffer in the window – but I don't know how.

In the meantime we can prevent the error by testing whether the original (terminal) buffer exists before trying to switch back to it.  However that would still mean any terminal buffers automatically close themselves.

**Closed** 2018-02-13 10:27 UTC
