### ISSUE TITLE
Hunk preview issue.

### ISSUE THREAD

**Issue by ovidius72** [airblade/vim-gitgutter#712] opened 2020-06-11 22:04 UTC
> What is the latest commit SHA in your installed vim-gitgutter?
e31e9bb35f7346caab4fcf972d44449bdfd3230a

> What vim/nvim version are you on?
NVIM v0.5.0-545-g6f4f38cd5

I have `gh` mapper to `<Plug>(GitGutterPreviewHunk)`.
When I'm in a modified line and press gh the hunk preview appears correctly. If i do this a second time I receive this error: 
``` 
Errore/i eseguendo function gitgutter#hunk#preview[3]..<SNR>113_hunk_op[62]..<SNR>113_preview[5]..<SNR>113_open_hunk_preview_window:                                       
riga   19:                                                                                                                                                                 
E5555: API call: Vim(call):E121: Undefined variable: w:history 

```
Then i press enter and the hunk preview is showed. I have the same problem with neovim 0.4.

**Comment by airblade** [comment] 2020-06-12 08:12
I can't reproduce this.  vim-gitgutter doesn't use a `w:history` variable, so I presume the problem is caused by an interaction with some other plugin.

All I can suggest is grepping your installed plugins for `history` and identifying the plugin in question that way.  Once we know what it is, we can try to figure out what the problem is.

**Comment by ovidius72** [comment] 2020-06-12 11:40
Thanks @airblade .I found `bufsurf.vim` is using the `w:history` variable.  However, I don't know why it conflicts with `gitgutter`. If you can find a solution it would be great. Thanks.

**Comment by airblade** [comment] 2020-06-15 10:16
This is the line your error message points to:

https://github.com/airblade/vim-gitgutter/blob/e31e9bb35f7346caab4fcf972d44449bdfd3230a/autoload/gitgutter/hunk.vim#L421

Perhaps setting the buffer's name triggers a `BufEnter` event?  Which would be [picked up by bufsurf](https://github.com/ton/vim-bufsurf/blob/e93829bf4618ee3b9c236d783abadb77be837eb6/plugin/bufsurf.vim#L171).

I don't quite understand why there's a problem with `w:history`, but does this fix the problem?

```
let g:BufSurfIgnore = 'gitgutter'
```

**Comment by ovidius72** [comment] 2020-06-15 10:59
Thanks. Unfortunately it doesn't work for me. Same error. I ended up disabling `BufSurf` and it works as expected. At the end I was not using that plugin too much.

**Comment by airblade** [comment] 2020-06-15 12:12
I installed BufSurf but still couldn't reproduce the error.  It sounds like you're not too concerned so I'll close the issue.

**Closed by airblade** 2020-06-15 12:12 UTC
