### ISSUE TITLE
gitgutter does not work when vim is started from a git alias in a git worktree

### ISSUE THREAD

**Issue by jreybert** [airblade/vim-gitgutter#447] opened 2017-11-20 11:02 UTC
### Config:
This problem occurs with:
* vim 7.4 and nvim 2.2
* Linux system
* git 2.15

### How to reproduce:
* In a git repo, create a git worktree: `git worktree add ../issue_447`
* add the alias `edit-modified = "!f() { git ls-files --modified | cut -f2 | sort -u ; }; vim $(f)"` in `~/.git/config`
* modify a file
* open the file with `git edit-modified`

### Long read:

In my git config, I have such aliases:
```
edit-modified = "!f() { git ls-files --modified | cut -f2 | sort -u ; }; vim $(f)"
```
If I edit my modified files witht he git alias, gitgutter signs won't show (and for the record, vim-airline git hints won't show either). If I edit these files from command line like:
```
$ vim some_file.c
```
gitgutter works (and vim-airline git hints too).

I tried to highlight the difference between the two vim sessions. I diffed the output of:
```
:let
```
and the only noticeable difference is that `vim-reload` seems loaded in normal vim session, and not in git alias session. `xolox#reload#version   0.6.17` is only defined in normal vim session. Seems to be a side effect, but may be a first lead...

**Comment by airblade** [comment] 2017-11-20 14:25
I followed your reproduction steps and when I opened the file with `git edit-modified` I saw the correct signs.

I'm using (Mac)Vim 8.0p1-3 and nvim 0.2.1, OSX, and git 2.11.0.

Is `grep` on the path in the git alias session?

**Comment by ajjahn** [comment] 2017-11-30 20:27
I experience this issue with a the simple alias `alias vim="nvim"`.

**Comment by jreybert** [comment] 2017-11-30 21:22
@airblade I missed your answer...

@ajjahn I also use this kind of alias in my bash session, I'll dig in that way.

@airblade 
> Is grep on the path in the git alias session?
What do you mean?

**Comment by airblade** [comment] 2017-12-01 09:48
The most common reason for no signs to show – without any error messages – is `grep` producing colourful output.  At a high level gitgutter does `git diff | grep` and if `grep` produces output with colours, the escape codes confuse vim.

You can determine whether this is the problem by disabling gitgutter's use of `grep`.  To do so, insert the line `let s:grep_available=0` in between [these two lines](https://github.com/airblade/vim-gitgutter/blob/1e60667322b7cd1bfcba98762fbba746a888d21a/autoload/gitgutter/diff.vim#L12-L13).

**Comment by airblade** [comment] 2018-02-12 14:45
I have just pushed a big refactor (5bfe5b9) – please could you update and see if the problem is fixed?

**Comment by airblade** [comment] 2018-02-12 14:46
You can now try without grep with `let g:gitgutter_grep=''`.

**Comment by airblade** [comment] 2018-02-14 11:21
I tried again with current master (85f6e13) and I can't reproduce the problem; neither with the worktree and `git edit-modified` nor with `alias vim="nvim"`.

I'll close this for now but happy to reopen if any further information comes to light.

**Comment by jreybert** [comment] 2018-02-14 12:30
Hi,

thanks for all the work! But unfortunately, I still get no gitgutter sign when opening files with `git edit-modified` in a worktree.

Is there any debug mode I can enable to give you some hint?

**Comment by airblade** [comment] 2018-02-14 15:04
Oh, you're opening files while in the linked working tree?  That wasn't in your repro steps ;)

Hmm, it still works for me whether I'm in the main working tree or a linked working tree.  As long as `git status` shows changes I seem them in gitgutter.

What does `:echo getbufvar('','gitgutter')` produce?  I assume its `path` will be `-2` which indicates gitgutter thinks the file isn't known to git.

You could also do `:GitGutterDebug` though it seems your issue is more subtle than usual :)

**Comment by jreybert** [comment] 2018-02-14 16:17
```
:echo getbufvar('','gitgutter')
{'hunks': [], 'path': -2, 'summary': [0, 0, 0], 'other_signs': [], 'dummy_sign': 0, 'gitgutter_signs': {}, 'tick': 3}                                                                                                                         
```

```
:GitGutterDebug
NVIM v0.2.3-277-gaa951b148
Build type: Release
LuaJIT 2.0.4

git version 2.15.1

grep (GNU grep) 2.20 Copyright (C) 2014 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.  Written by Mike Haertel and others, see <http://git.sv.gnu.org/cgit/grep.git/tree/AUTHORS>.
Usage: grep [OPTION]... PATTERN [FILE]...Search for PATTERN in each FILE or standard input.PATTERN is, by default, a basic regular expression (BRE).Example: grep -i 'hello world' menu.h main.cRegexp selection and interpretation:  -E, --extended-regexp     PATTERN is an extended regular expression (ERE)  -F, --fixed-strings       PATTERN is a set of newline-separated fixed strings  -G, --basic-regexp        PATTERN is a basic regular expression (BRE)  -P, --perl-regexp         PATTERN is a Perl regular expression  -e, --regexp=PATTERN      use PATTERN for matching  -f, --file=FILE           obtain PATTERN from FILE  -i, --ignore-case         ignore case distinctions  -w, --word-regexp         force PATTERN to match only whole words  -x, --line-regexp         force PATTERN to match only whole lines  -z, --null-data           a data line ends in 0 byte, not newlineMiscellaneous:  -s, --no-messages         suppress error messages  -v, --invert-match        select non-matching lines  -V, --version             display version information and exit      --help                display this help text and exitOutput control:  -m, --max-count=NUM       stop after NUM matches  -b, --byte-offset         print the byte offset with output lines  -n, --line-number         print line number with output lines      --line-buffered       flush output on every line  -H, --with-filename       print the file name for each match  -h, --no-filename         suppress the file name prefix on output      --label=LABEL         use LABEL as the standard input file name prefix  -o, --only-matching       show only the part of a line matching PATTERN  -q, --quiet, --silent     suppress all normal output      --binary-files=TYPE   assume that binary files are TYPE;                            TYPE is 'binary', 'text', or 'without-match'  -a, --text                equivalent to --binary-files=text  -I                        equivalent to --binary-files=without-match  -d, --directories=ACTION  how to handle directories;                            ACTION is 'read', 'recurse', or 'skip'  -D, --devices=ACTION      how to handle devices, FIFOs and sockets;                            ACTION is 'read' or 'skip'  -r, --recursive           like --directories=recurse  -R, --dereference-recursive                            likewise, but follow all symlinks      --include=FILE_PATTERN                            search only files that match FILE_PATTERN      --exclude=FILE_PATTERN                            skip files and directories matching FILE_PATTERN      --exclude-from=FILE   skip files matching any file pattern from FILE      --exclude-dir=PATTERN directories that match PATTERN will be skipped.  -L, --files-without-match print only names of FILEs containing no match  -l, --files-with-matches  print only names of FILEs containing matches  -c, --count               print only a count of matching lines per FILE  -T, --initial-tab         make tabs line up (if needed)  -Z, --null                print 0 byte after FILE nameContext control:  -B, --before-context=NUM  print NUM lines of leading context  -A, --after-context=NUM   print NUM lines of trailing context  -C, --context=NUM         print NUM lines of output context  -NUM                      same as --context=NUM      --group-separator=SEP use SEP as a group separator      --no-group-separator  use empty string as a group separator      --color[=WHEN],      --colour[=WHEN]       use markers to highlight the matching strings;                            WHEN is 'always', 'never', or 'auto'  -U, --binary              do not strip CR characters at EOL (MSDOS/Windows)  -u, --unix-byte-offsets   report offsets as if CRs were not there                            (MSDOS/Windows)'egrep' means 'grep -E'.  'fgrep' means 'grep -F'.Direct invocation as either 'egrep' or 'fgrep' is deprecated.When FILE is -, read standard input.  With no FILE, read . if a command-line-r is given, - otherwise.  If fewer than two FILEs are given, assume -h.Exit status is 0 if any line is selected, 1 otherwise;if any error occurs and -q is not given, the exit status is 2.Report bugs to: bug-grep@gnu.orgGNU Grep home page: <http://www.gnu.org/software/grep/>General help using GNU software: <http://www.gnu.org/gethelp/>

updatetime=4000
shell=/bin/bash
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

FYI, `:GitGutterDebug` produces some `^@` characters in `grep --version` output, which truncate the copy/paste: try to copy with the `GitGutterDebug` output with `"+y` and paste in your browser with `^V`, the output should be truncated right after `grep (GNU grep) 2.20`

**Comment by airblade** [comment] 2018-02-14 17:23
Have you tried `let g:gitgutter_grep=''` yet?

**Comment by airblade** [comment] 2018-02-14 19:50
Actually, grep is irrelevant here.  The `path` is `-2` which means that `cd /path/to/dir && git ls-files --error-unmatch --full-name some_file.c` is exiting with a non-zero status code.  In other words, git says it doesn't know anything about `some_file.c`.

(If you turn on logging `let g:gitgutter_log=1` you will see the exact command vim is running, in a log file in your gitgutter installation directory.)

What happens if you run the command manually?  I.e. `:!cd /path/to/dir && git ls-files ...etc`?

**Comment by jreybert** [comment] 2018-02-15 10:16
Soooo, `:!cd /path/to/dir && git ls-files ...` returns an error when executed from `git edit-modified`, and returns the absolute path of the file when executed from a classic vim/nvim session or from the bash.

I am starting digging into the differences between the vim environments.

There is no real diffs between the environments between the two sessions (I dump the environment with `:let` command).
Relevant diffs are gitgutter and airline buffer variables diffs. airline also have issue to recognize the file in the git repository. These diffs are consequences, not the cause.

No diff in options: `:set all` `:setlocal` are exactly the same.

I am lacking imagination here... If you have any idea...

**Comment by airblade** [comment] 2018-02-15 11:25
Does `!git --version` give you the same version in the two environments?  I'm wondering whether the shell spawned by your `git edit-modified` uses an old version of git which isn't compatible with your git config.

**Comment by jreybert** [comment] 2018-02-15 12:00
Good lead, but git is the same in both sessions.

**Comment by airblade** [comment] 2018-02-15 12:05
Ok, what is the exact error you get with `:!cd /path/to/dir && git ls-files ...` from `git edit-modified`?

**Comment by jreybert** [comment] 2018-02-15 12:11
```
:!cd /absolute/path && git ls-files --error-unmatch --full-name file.h            
                                                                                                                      
error: pathspec 'file.h' did not match any file(s) known to git.                                                 
Did you forget to 'git add'?                                                                                          
shell returned 1                                                                                                      
```

That's weird, other git commands like `:!git rev-parse --show-toplevel` or `:!git status` work perfectly well in both sessions.

**Comment by airblade** [comment] 2018-02-15 14:44
Weird indeed.

Does `!cd /absolute/path && git status` work?

**Comment by airblade** [comment] 2018-02-16 10:50
I'm closing this because it doesn't look like a problem with vim-gitgutter.

However I am curious to hear what the problem/solution is once you have fixed it :)

**Closed by airblade** 2018-02-16 10:50 UTC

**Comment by jreybert** [comment] 2018-02-16 11:49
Sure, I'll update this ticket once I found the cause of the problem.

**Comment by SevereOverfl0w** [comment] 2025-09-04 11:00
I just ran into this. The main problem seems to be something to do with `GIT_DIR` env var.

```
/path/to/repo/worktrees/branch-name branch-name 31s
❯ git -C /path/to/repo/worktrees/branch-name/src/module/submodule ls-files -v --error-unmatch --full-name -z -- file.clj
H src/module/submodule/file.clj%                                                                           
/path/to/repo/worktrees/branch-name branch-name
❯ GIT_DIR=/path/to/repo/.git/worktrees/branch-name/ git -C /path/to/repo/worktrees/branch-name/src/module/submodule ls-files -v --error-unmatch --full-name -z -- file.clj
error: pathspec 'file.clj' did not match any file(s) known to git
Did you forget to 'git add'?
```

I can work around it somewhat by doing `GIT_WORK_TREE=$PWD git alias`, or by updating my alias to `env -u GIT_DIR nvim ...`.

This doesn't seem to affect an alias like:

```
	lss = ls-files -v --error-unmatch --full-name --
```

but it does affect an alias like:

```
	lsss = !sh -c \"git ls-files -v --error-unmatch --full-name -- $@\" -
```
