### ISSUE TITLE
only add to sign column if in a git repo

### ISSUE THREAD

**Issue by nhooyr** [airblade/vim-gitgutter#304] opened 2016-02-08 21:33 UTC
title.

**Comment by airblade** [comment] 2016-02-09 10:17
Please can you give me steps to reproduce your problem?

**Comment by nhooyr** [comment] 2016-02-09 12:02
@airblade no problem, just an idea. Only add the dummy signs if we are in a git repo (`let g:gitgutter_sign_column_always = 1`)

**Comment by nhooyr** [comment] 2016-02-13 19:48
@airblade like if I run `:PlugUpdate`. Then run its again, for some reason gitgutter activates in that window and adds a bunch of seemingly random addition signs.

<img width="1440" alt="screen shot 2016-02-13 at 2 48 43 pm" src="https://cloud.githubusercontent.com/assets/10180857/13029688/e5aef5ce-d260-11e5-8f0a-511fd3aef4d1.png">

**Comment by airblade** [comment] 2016-04-22 09:07
I can't reproduce this (using junegunn/vim-plug@41de3c7).  I wonder whether it was fixed by 78d83c7?

Please could you update vim-gitgutter and try again?

**Comment by mrleolink** [comment] 2016-04-22 09:15
Did you try to open a file which has special characters in its name like "[" with vim?


Anyway, this is my vim-gitgutter status:

<img width="581" alt="screen shot 2016-04-22 at 6 13 58 pm" src="https://cloud.githubusercontent.com/assets/991367/14737241/15f8b19e-08b6-11e6-82c2-91282dbdbaa3.png">

**Comment by airblade** [comment] 2016-05-18 15:51
I can't reproduce the `:PlugUpdate` problem.  Let me know if it comes up again and please post steps to reproduce.  Thanks!

Regarding only adding the dummy sign if in a git repo, I can see the merit of that but I often have non-repo files open alongside repo files and I want the line number columns to line up.  Also since this behaviour has been established for a while I'm reluctant to change it.

**Closed by airblade** 2016-05-18 15:51 UTC
