### ISSUE TITLE
Loading takes 4.5x longer with FISH vs BASH

### ISSUE THREAD

**Issue by LukeChannings** [airblade/vim-gitgutter#531] opened 2018-06-19 11:11 UTC
With the default shell set to fish, vim-gitgutter loads very slowly.

Profile excerpt with `set shell=fish`:

```
223.547  121.853: opening buffers
224.394  000.404  000.404: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter.vim
225.680  000.236  000.236: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/async.vim
226.197  000.255  000.255: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/debug.vim
247.461  019.762  019.762: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/diff.vim
```

and without:

```
211.675  108.961: opening buffers
212.575  000.454  000.454: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter.vim
213.884  000.245  000.245: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/async.vim
214.450  000.330  000.330: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/debug.vim
402.039  185.952  185.952: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/diff.vim
```

**Comment by airblade** [comment] 2018-06-19 11:16
Sourcing `diff.vim` executes [this line](https://github.com/airblade/vim-gitgutter/blob/a986ab054788776dca269d6c289b470255d54e8c/autoload/gitgutter/diff.vim#L7):

```viml
  call system(g:gitgutter_git_executable.' -c foo.bar=baz --version')
```

Presumably that is the cause of the slow down.

If you add `return 1` after that line, does the slowdown go away?

**Comment by LukeChannings** [comment] 2018-06-19 11:20
Nope, looking at the order of execution, it seems the slowdown is in `debug.vim`, `diff.vim` only takes ~10ms to run.

**Comment by LukeChannings** [comment] 2018-06-19 11:20
This is with Vim 8.1.1, fyi.

**Comment by LukeChannings** [comment] 2018-06-19 11:27
Oh, apologies, I stupidly did:

```vim
" True for git v1.7.2+.
function! s:git_supports_command_line_config_override() abort
  call system(g:gitgutter_git_executable.' -c foo.bar=baz --version')
  return 1
endfunction
```

Instead of

```vim
" True for git v1.7.2+.
function! s:git_supports_command_line_config_override() abort
  return 1
endfunction
```

With the latter change the startup time is much improved:

```
232.815  000.409  000.409: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter.vim
234.351  000.275  000.275: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/async.vim
234.847  000.253  000.253: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/debug.vim
237.286  000.842  000.842: sourcing /Users/44092098/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/diff.vim
```

**Comment by airblade** [comment] 2018-06-19 12:05
The next step is to determine whether it the `system()` call that's slow, or git.  If you update the function like this, how does the profile look?

```viml
function! s:git_supports_command_line_config_override() abort
  call system('ls')
  return !v:shell_error
endfunction
```

**Comment by LukeChannings** [comment] 2018-06-20 10:50
It looks like it's the `system()` call to me.

```vim
function! s:git_supports_command_line_config_override() abort
  call system('ls')
  return !v:shell_error
endfunction
```

Without `set shell=fish`:

```
240.483  000.434  000.434: sourcing /Users/44092098/.local/share/vim/plugged/vim-gitgutter/autoload/gitgutter.vim
241.894  000.342  000.342: sourcing /Users/44092098/.local/share/vim/plugged/vim-gitgutter/autoload/gitgutter/async.vim
242.654  000.265  000.265: sourcing /Users/44092098/.local/share/vim/plugged/vim-gitgutter/autoload/gitgutter/debug.vim
276.170  031.862  031.862: sourcing /Users/44092098/.local/share/vim/plugged/vim-gitgutter/autoload/gitgutter/diff.vim
```

With `set shell=fish`:

```
242.571  000.418  000.418: sourcing /Users/44092098/.local/share/vim/plugged/vim-gitgutter/autoload/gitgutter.vim
243.936  000.299  000.299: sourcing /Users/44092098/.local/share/vim/plugged/vim-gitgutter/autoload/gitgutter/async.vim
244.720  000.347  000.347: sourcing /Users/44092098/.local/share/vim/plugged/vim-gitgutter/autoload/gitgutter/debug.vim
455.025  208.593  208.593: sourcing /Users/44092098/.local/share/vim/plugged/vim-gitgutter/autoload/gitgutter/diff.vim
```

**Comment by svanburen** [comment] 2018-09-05 20:27
hi,

I've recently had a similar issue to this. I checked, and `set shell` was set to `/usr/local/bin/zsh`. I've set my shell to `/bin/bash` and it seems to clear up the issue - I'm somewhat surprised though that shelling out is needed to get the `git --version`.

Anyways, cheers for the plugin.

**Comment by airblade** [comment] 2019-01-16 15:49
Closing because this has gone quiet.  Happy to reopen if it's still a problem.

**Closed by airblade** 2019-01-16 15:49 UTC
