### ISSUE TITLE
signcolumn background color

### ISSUE THREAD

**Issue by breuerfelix** [airblade/vim-gitgutter#696] opened 2020-04-19 09:26 UTC
There is a Problem with SignColumn background color described here: https://github.com/sainnhe/edge/issues/6

also here: https://github.com/sainnhe/gruvbox-material/issues/33

just wanna leave that here maybe it is a small fix :)  
in the first issue the author of the colorscheme is describing thats the error. that is actually me using another plugin. thats sad, so maybe this will help in the future :)

**Comment by airblade** [comment] 2020-04-19 15:08
vim-gitgutter sets the signs' foreground colours to the colour scheme's Diff* foreground colours, and the background colours to the SignColumn's colour.

In both your linked issues the signs' background colour is a little darker than the SignColumn.  I'll have to look into why this is.

**Comment by airblade** [comment] 2020-04-25 19:04
@breuerfelix Please could you update vim-gitgutter and let me know if the problem is fixed?

**Comment by airblade** [comment] 2020-04-28 08:05
This was indeed fixed by 8db2fc5.

**Closed by airblade** 2020-04-28 08:05 UTC

**Comment by airblade** [comment] 2020-04-30 18:54
It turns out I was wrong: I thought the sign column in that colorscheme was supposed to be white, not grey.  The real fix is in 0da302c.

**Comment by camilstaps** [comment] 2020-05-14 09:19
With the [solarized](https://github.com/altercation/vim-colors-solarized) color scheme, I need to do the following (from https://stackoverflow.com/a/7383051):

```vim
autocmd ColorScheme * highlight! link SignColumn LineNr
```

Simply `highlight! link SignColumn LineNr` did not work. It may be that the order of the imports matters, but I couldn't find an order that worked without using the callback. That may be an issue  for the colorscheme rather than vim-gitgutter, of course.

**Comment by leesmith** [comment] 2020-05-19 21:10
@camilstaps Thanks so much for the `autocmd`! I'm using the beloved solarized colorscheme as well and this was exactly what I needed to "fix" the background color.

Here's what it looks like before using the `autocmd`:
<img width="705" alt="Screen Shot 2020-05-19 at 4 08 01 PM" src="https://user-images.githubusercontent.com/90055/82378582-f335ae80-99ea-11ea-8ce9-034fe4c25cf3.png">

**Comment by airblade** [comment] 2020-05-20 08:28
@camilstaps @leesmith When I use solarized, `highlight! link SignColumn LineNr` works as expected.

I believe you are seeing what you see because you have `syntax on` after your colorscheme declaration:

https://github.com/leesmith/dotfiles/blob/8d2d18b5e9d0e6ed2976128ee7e221e70233eb84/nvim/init.vim#L92

I suggest changing `syntax on` to `syntax enable` and moving it to the very top of your vimrc.

**Comment by camilstaps** [comment] 2020-05-20 10:15
I did some more debugging and for me it was not `syntax enable` but `set background=dark` (I set the background automatically depending on whether I'm in the train or not).

A minimal .vimrc to reproduce:

```vim
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim', {'pinned': 1}
Plugin 'airblade/vim-gitgutter'

call vundle#end()

syntax enable

colorscheme solarized
highlight! link SignColumn LineNr
set background=dark " or light
```

Do you have an idea how to prevent this? I tried adding `default` to the `SignColumn` declaration in solarized.vim, but that is not enough. But it may be a problem that should be solved in solarized.vim of course.

**Comment by airblade** [comment] 2020-05-20 10:16
Switch on syntax and set the background before you declare your colorscheme.

**Comment by camilstaps** [comment] 2020-05-20 10:18
That works, but what if I want to change the background during a session?

**Comment by airblade** [comment] 2020-05-20 10:19
Then you'll need the colorscheme autocmd.  From `:help 'background'`:

> 	When a color scheme is loaded (the "g:colors_name" variable is set)
>	setting 'background' will cause the color scheme to be reloaded.

**Comment by camilstaps** [comment] 2020-05-20 10:20
OK, thank you for the explanation!

**Comment by hasufell** [comment] 2020-06-14 20:40
> `autocmd ColorScheme * highlight! link SignColumn LineNr`

I never needed that workaround before. What changed?

**Comment by airblade** [comment] 2020-06-15 09:01
@hasufell 0da302c28a08fe62c31c77ac854914affd2180b8

**Comment by ayroblu** [comment] 2020-06-25 06:17
Guess I'm here like everyone else, because my editor changed during a PlugUpdate and using solarised colorscheme. 
Some unimportant facts: the `highlight! link SignColumn LineNr` did not work for "+"s when I ran it adhoc, I had to put it in my `.vimrc`, not sure why. I don't need the autocmd, just running `highlight! link SignColumn LineNr` as prescribed after the colorscheme command. Also fwiw I set my colorscheme after plugins

The major reason I use this plugin is that it was the only one that worked out of the box for me. That is not quite true anymore, but one line configuration is fine. cudos to airblade I realise it's hard to push out changes like this because of how behind the scenes updates work

**Comment by sadid** [comment] 2020-09-26 01:49
On updated vim and git-gutter plugin I could only fix the gray background problem using 
```
set background=dark
colorscheme solarized
autocmd ColorScheme * highlight! link SignColumn LineNr
```

The `autocmd ColorScheme *` was needed to fix the problem. Is there a way to get rid of it?

**Comment by idwer** [comment] 2021-01-27 15:19
This commit changed theme behaviour: https://github.com/airblade/vim-gitgutter/commit/0da302c28a08fe62c31c77ac854914affd2180b8

Instead of showing '_', '~' or '+' in the left margin when there are differences,
a (full length) white bar is present. In this white bar, only '_' is visible when lines are deleted.

The command ':highlight! link SignColumn LineNr' lets '_' appear and hides '~' or '+'.

OS: FreeBSD 14-CURRENT
Packages:
git-2.30.0
vim-console-8.2.2263_1
bash-5.1.4_1
~/.vimrc is empty (not present)

vim-gitgutter is checked out in ~/.vim/pack/airblade/start/vim-gitgutter/
