### ISSUE TITLE
Signs "bleed through" to terminal buffer.

### ISSUE THREAD

**Issue by raichoo** [airblade/vim-gitgutter#314] opened 2016-02-29 09:55 UTC
Hi, I'm using a recent version of neovim `NVIM v0.1.3-269-g9c4b34b` and I'm having the following effect.

When switching to a terminal buffer the signs of an "underlying" buffer bleed through to the terminal and it ends up looking like this:

![screenshot from 2016-02-29 10-49-11](https://cloud.githubusercontent.com/assets/151506/13391090/ad810c36-ded2-11e5-8cfe-e6a61c224257.png)

These signs are coming from another buffer:

![screenshot from 2016-02-29 10-49-29](https://cloud.githubusercontent.com/assets/151506/13391105/c0ede546-ded2-11e5-81c7-a928bd34b185.png)

Other non-terminal buffers are not affected and display their signs correctly.

Kind regards,
raichoo

**Comment by airblade** [comment] 2016-03-07 09:12
I have no idea what's causing this, unfortunately.  Do you get the same effect when placing a sign manually?  E.g.:

```viml
:sign define name=foo text=>>
:sign place 42 line=1 name=foo buffer=1
```

(Replace the buffer number with the appropriate value.)

**Comment by raichoo** [comment] 2016-03-07 09:51
The sign I put there myself (using your commands) does not "bleed" through. The gitgutter signs however do.

**Comment by airblade** [comment] 2016-03-07 10:00
How odd.

The only difference between the manual sign and gitgutter's signs are the latter's have foreground and background colours set.

If you edit the [highlight](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/highlight.vim) file to get rid of the `guibg` and `ctermbg` (lines 14-16), does that make a difference?

**Comment by raichoo** [comment] 2016-03-07 10:10
I've commented these lines out, same effect. I've noticed that some redraw event need to be triggered for this to happen. Switching desktops back and forth on Gnome3 triggers that event instantly, otherwise I have to wait for a while for this to happen (maybe the update timeout waiting in the background?).
I'm making wild guesses here, but I'm trying to provide as much information as possible.

**Comment by airblade** [comment] 2016-03-07 10:13
I appreciate that.  Like I said originally, I have no idea what's going on.  Maybe someone on the neovim end who knows the terminal buffer implementation might be able to shed some light?

**Comment by raichoo** [comment] 2016-03-07 10:20
I don't know to be honest. It looks like this issue is related to gitgutter, since I've only encountered this since I've started using it. This certainly won't stop me from using it in the future, it's just somewhat annoying. Anyway, maybe the terminal works in a way that needs some special handling, but I'm afraid I cannot answer that.

**Comment by airblade** [comment] 2016-03-07 10:26
Can you give me steps to reproduce the problem?  I've never used neovim's terminal buffers.

**Comment by raichoo** [comment] 2016-03-07 10:34
Sure, it might take less to reproduce it, but this is what I do.

- create a new git repo
- add an empty file and commit it
- open file with `nvim`
- split window vertically
- issue `:terminal` in right split window
- write some stuff into the previously empty file, to make signs show up
- trigger redraw event (or whatever it is that causes this)

These are the **exact** steps I'm doing to make this happen.

**Comment by airblade** [comment] 2016-03-07 10:36
In step 6, are you writing stuff in the left split?  And in step 7, triggering the redraw in the left split?

Where do the signs bleed through: in the left or right split?

**Comment by raichoo** [comment] 2016-03-07 10:41
Yep, I'm writing into the left split. It does not matter where you are when the "redraw" happens. I've tried to trigger it using `CTRL-l` sadly that does not do it.

**Comment by raichoo** [comment] 2016-03-07 10:45
I can trigger the "redraw" by simply re-sizing the window.

**Comment by airblade** [comment] 2016-03-08 10:15
I can't see how this is caused by vim-gitgutter: the plugin uses Vim's signs commands in the normal way.  It's odd that the problem doesn't occur with a manually placed sign but I can't see anything unusual vim-gitgutter might be doing.

**Comment by raichoo** [comment] 2016-03-08 18:24
Hm, I guess I'll post a link to this issue to the `neovim` repo. Could you leave this open until we know what's going on?

**Comment by airblade** [comment] 2016-04-20 10:24
This isn't a vim-gitgutter issue so I'm going to close it.

**Closed** 2016-04-20 11:16 UTC
