### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by luisdavim** [airblade/vim-gitgutter#335] opened 2016-05-10 21:29 UTC
Hi,

I update the vim plugins I use frequently and since a few days back gitgutter has become very slow making vim unresponsive, even in small files and repos with not that much history.

I tested with both NVIM 0.1.5-dev and VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28) on ubuntu 16.04, both with the same vimrc file and gitgutter is slow with both of them.

After disabling gitgutter vim becomes fast again.

Please let me know if you need any more information like a profile trace, you can check my vimrc here: https://github.com/luisdavim/dotfiles/blob/master/files/vimrc

Thanks,
Luis

**Comment by airblade** [comment] 2016-05-11 09:43
That's an old version of Vim; it's almost 2000 patches behind the latest.  The plugin will run better on a more recent Vim.  However I don't think that's relevant to this issue because your Neovim is up to date.

Can you use git-bisect to identify the commit which made things slow for you?

A profile would also help.  Here are [some instructions](https://github.com/airblade/vim-gitgutter/wiki/How-to-profile-vim-gitgutter).

Are your repos on the local file system or across a network somewhere?

**Comment by luisdavim** [comment] 2016-05-11 09:48
I usually use nvim that version of vim is the one that comes with ubuntu, I just used it to test.
This issue is not related to a specific git repo, it happens with all my repos, even recent ones with few commits and small files.

I'll send you a profile later.

Thanks,
Luis

**Comment by luisdavim** [comment] 2016-05-11 16:52
Hi,

Here is the profile.

Luis
[gitgutter.txt](https://github.com/airblade/vim-gitgutter/files/259772/gitgutter.txt)

**Comment by airblade** [comment] 2016-05-12 09:33
Thanks for the profile, Luis.

Surprisingly the slowness comes from removing signs.  From line 196 in the `gitgutter#sign#find_current_signs()` function:

```
   10              3.271938           execute "sign unplace" gitgutter_signs[line_number].id
```

I reckon this is a NeoVim regression so I'll try to put together a simple demo and open an issue there.

**Comment by airblade** [comment] 2016-05-12 09:59
I have just upgraded my NeoVim to NVIM v0.1.5-359-gd02cfe8.  I profiled the plugin and there was no slowness anywhere; even the `execute "sign uplace" ...` line was fast.

I looked at your vimrc but I can't see anything that would affect signs.

What happens if you save this script as demo.vim and run it with `nvim -S demo.vim`:

```viml
let bufnr = bufnr('')
sign define Foo text=*

let num = 100

for i in range(1, num)
  execute "sign place ".i." line=".i." name=Foo buffer=".bufnr
endfor

let start = reltime()
for i in range(1, num)
  execute "sign unplace ".i
endfor
echom reltimestr(reltime(start))."s to remove ".num." signs"
```

On my system it takes around 0.000457s to remove 100 signs.

**Comment by luisdavim** [comment] 2016-05-12 11:30
Hi,

I've updated my nvim and gitgutter and ran your script:

0.000320s to remove 100 signs

The slowness seams to be gone.

Thanks.

**Comment by airblade** [comment] 2016-05-12 13:05
That's good news.  I'll close this now but do let me know if the plugin runs slowly again.

**Closed by airblade** 2016-05-12 13:05 UTC
