### ISSUE TITLE
Slowness only w/ multiple windows

### ISSUE THREAD

**Issue by avonmoll** [airblade/vim-gitgutter#501] opened 2018-03-14 18:08 UTC
> What is the latest commit SHA in your installed vim-gitgutter?
380e7935b7b4cac10d3bc3031d492deaf5008495
> What vim/nvim version are you on?
8.0 (using MacVim installed from brew)
> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
N/A
> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?
N/A

I'm brand new to vim in general, so please forgive me if I'm making obvious mistakes. When I have two documents open in split windows the computation of the line-by-line status seems to get very slow. So slow that the editor is blocked for a couple of seconds as I see signs in the gutter changing/disappearing. I do not see this type of behavior when I have just one window open.

I poked around a bit and saw your information about making a profile, so I went ahead and did so: [gitgutter.log](https://gist.github.com/avonmoll/0a9131a52e5fad48a4f9141c105eb52f#file-gitgutter-log).
 
I also ran the `demo.vim` from [another slowness issue](https://github.com/airblade/vim-gitgutter/issues/335#issuecomment-218712876). The time to run the demo was similar to what you guys had.

If it's helpful, here is a list of plugins I'm using:
- fugitive
- jedi
- minibufexpl
- gruvbox
- lightline
- nerdtree
- nerdtree-git-plugin
- commentary
- surround
- vim-pandoc
- vimtex

**Comment by airblade** [comment] 2018-03-14 19:47
Thanks for the detailed report.  It sounds like an unusual problem and I can't think why having more than one window would slow things down like this.

[This line from the profile](https://gist.github.com/avonmoll/0a9131a52e5fad48a4f9141c105eb52f#file-gitgutter-log-L3115) stands out:

```
count  total (s)   self (s)
 1933             20.182092       execute "sign unplace" id
```

– which is 10.4ms per sign to remove.  This seems a little slow but as it's a built-in Vim function there's no way to speed it up.

Right now I'm not sure what the problem is so forgive the random questions:

Are you using MacVim in its gui form or in the terminal (via `mvim -v`)?

Are your diffs particularly large?

Are you able to reproduce this with gitgutter as your only plugin?

Is your vimrc online somewhere?

**Comment by avonmoll** [comment] 2018-03-14 19:55
> Are you using MacVim in its gui form or in the terminal (via mvim -v)?

Using `mvim -v`

> Are your diffs particularly large?

About 20-30 changed lines in a latex file that's about 200 lines long. This doesn't seem like a big diff to me, but I'm not sure.

> Are you able to reproduce this with gitgutter as your only plugin?

Is there a quick/easy way to open vim with just gitgutter?

> Is your vimrc online somewhere?

No, it's local (`~/.vimrc`)

**Comment by airblade** [comment] 2018-03-14 20:20
> About 20-30 changed lines in a latex file that's about 200 lines long.

I agree, that's not a big diff.  The signs should re-render almost instantly.

> Is there a quick/easy way to open vim with just gitgutter?

If you're using a plugin manager it should be fairly straightforward.  If your plugins are installed manually, you could move all the other plugins' directories out of the way.

**Comment by airblade** [comment] 2018-03-14 20:32
Does it make a difference if you use gui macvim?

How about if you use a different terminal?

**Comment by airblade** [comment] 2018-03-15 11:42
I updated the demo.vim script and added it [here](https://github.com/airblade/vim-gitgutter/blob/master/unplace.vim).

For me, terminal MacVim is consistently two times slower than gui MacVim.

Although we can't speed up `sign unplace` itself, I wondered whether setting `lazyredraw` would help – it doesn't.  I also wondered whether we could execute multiple `sign unplace`s at once, but I couldn't find a way to make that work.

**Comment by airblade** [comment] 2018-03-15 11:52
I suppose having more than one window slows things down because when Vim removes a sign from a buffer, it has to loop over all windows and when a window's buffer is the buffer in question, remove the sign from the sign column.

**Comment by avonmoll** [comment] 2018-03-15 13:10
I'm going to try out some of the suggestions you made. I'm also going to install neovim and try it out on there.

**Comment by airblade** [comment] 2018-03-16 09:05
Thanks for reporting your results.  I wonder too why your setup/system is affected.

The time needed to unplace a sign will be proportional to the time taken to redraw each affected window.  Does it make any difference if you turn off syntax highlighting?  Not that you would normally; I'm just trying to isolate the problem.

There's nothing we can do from the plugin to speed up `sign unplace`; all we can do is call it as little as possible – which we do.

The next step would be to improve Vim's implementation.  For example, it looks like the relevant window(s) are redrawn after every `sign unplace`; perhaps it would help to allow `sign unplace` to take multiple sign ids, and only redraw after all the signs have been removed.  Or maybe the window redrawing code could be optimised to only redraw the sign column instead of the entire window.

The `sign unplace` implementation is [here](https://github.com/vim/vim/blob/8a3bb56230d220b8e1b4dcca517ed95f5341b8c7/src/ex_cmds.c#L7724-L7735).  It calls:

```c
buf_delsign(curwin->w_buffer, id);
update_debug_sign(curwin->w_buffer, curwin->w_cursor.lnum);
```

`buf_delsign` is [here](https://github.com/vim/vim/blob/8a3bb56230d220b8e1b4dcca517ed95f5341b8c7/src/buffer.c#L5911-L5949).

`update_debug_sign` is [here](https://github.com/vim/vim/blob/f708ac592f47100a36f2bc12ec98ea6357fdfa27/src/screen.c#L971-L1025).

The `win_update` code is [here](https://github.com/vim/vim/blob/f708ac592f47100a36f2bc12ec98ea6357fdfa27/src/screen.c#L1099-L2351).  It looks expensive.

Anyway, it would be nice to improve this but as it's not something the plugin can do anything about, I'm going to close it.

**Comment by airblade** [comment] 2018-03-16 10:21
I thought of a way we could call `sign unplace` fewer times.

If:

- your Vim supports `sign unplace *` (which recent ones do);
- and there are no non-gitgutter signs in the buffer;
- and we want to remove most but not all signs;

– at some threshold it will be quicker to remove all the signs and add back the ones we want to keep, than to remove the ones we no longer want.

The threshold depends on the number of signs to remove, the number of signs to keep, and the relative speeds of `sign unplace *`, `sign add`, and `sign unplace id`.

For example if we assume the sign commands all take the same amount of time, and

    (remove all) + (no. signs to keep) < (no. signs to remove)

– we should switch strategy.

I would need to do some profiling to establish the relative costs of each sign command, although I expect they are similar.

I also [asked on vim_dev](https://groups.google.com/d/msg/vim_dev/piG8Xbxf0uo/629l17rDCAAJ) whether it would be possible to speed up Vim's implementation.

**Comment by avonmoll** [comment] 2018-03-16 13:26
It appears that when vim is taking it's time to remove signs it starts by assuming all lines are new and then gradually removes the signs that should not be there. If I understand correctly (and if you commit fairly often) then you might benefit from the new strategy (assuming the times for those operations match our intuition).

Thanks for all the help and digging so far!

**Comment by airblade** [comment] 2018-03-16 14:28
> ...it starts by assuming all lines are new and then gradually removes the signs that should not be there.

That would be a bug.  It's supposed to just display the necessary signs the first time round, and subsequently add/remove/update any that have changed.

Is there any chance you could post an [asciicast](https://asciinema.org) so I can see what you're seeing?

**Comment by airblade** [comment] 2018-03-16 17:02
That's good news.  I'll take this chance to re-close the issue!

As an aside, you might find it easier to install/update/uninstall plugins using a plugin manager.  There isn't one built into Vim but a couple of good ones are [vim-plug](https://github.com/junegunn/vim-plug/) and [minpac](https://github.com/k-takata/minpac) (see [VimCast](http://vimcasts.org/episodes/minpac/)).  Having said that, I just use a [bash script](https://github.com/airblade/voom).

Anyway, glad the problem has gone away.

**Closed by airblade** 2018-03-16 17:02 UTC
