### ISSUE TITLE
After recent upgrade, diff color section is not working as expected.

### ISSUE THREAD

**Issue by mechanicles** [airblade/vim-gitgutter#580] opened 2019-02-03 06:46 UTC
> What is the latest commit SHA in your installed vim-gitgutter?

=> afa4f2ddf0fecb37914ec37357636abb18013422

> What vim/nvim version are you on?

=> Vim (MacVim)

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2018 08:58:43)
macOS version     
```

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

=> Signs are getting displayed, but still, I am providing the path here `vim/vimrc`

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

=> 🤔 

After upgrading vim-gitgutter, now diff section is working differently I guess. You can see this image,

<img width="203" alt="jellybeans" src="https://user-images.githubusercontent.com/77895/52173515-2c252200-27ac-11e9-8f99-442fa8d5fcdc.png">

Instead of background colours, it should change the colours of the signs text/symbol based on the Jellybeans colorscheme. The author says that they have already set those colours https://github.com/nanotech/jellybeans.vim/issues/79 (I have created an issue for the same)

**Comment by airblade** [comment] 2019-02-04 14:49
Please can you upgrade to fd834e4 and try again?

**Comment by jam1garner** [comment] 2019-02-04 20:49
Not sure if this is the same issue, but updating broke foreground colors for me (I'm on fd834e4)

![image](https://user-images.githubusercontent.com/8260240/52236036-b8f6db00-2893-11e9-893e-8cb6b2253a4b.png)

And here's my PlugDiff from updating, sorry that I haven't updated in a while but if you'd like me to bisect for the breaking commit let me know!
![image](https://user-images.githubusercontent.com/8260240/52236277-610ca400-2894-11e9-8445-efd6390fa586.png)

**Comment by airblade** [comment] 2019-02-05 11:24
@jam1garner @mechanicles Please could you be more specific?

If you or your colourscheme has defined the highlight groups `GitGutterAdd` / `GitgutterChange` / `GitGutterDelete`, your signs should be using those colours.

If neither you nor your colourscheme has defined the `GitGutterAdd` etc highlight groups, your signs' foreground colours should be those of your colourscheme's `DiffAdd` etc highlight groups.

You can do `:verbose highlight GitGutterAdd` and `:verbose highlight DiffAdd` to see what is actually defined in your setup.

**Comment by jam1garner** [comment] 2019-02-06 05:06
@airblade Hm well my colorscheme has definitely not changed since I maintain my own colorscheme, but modifying DiffAdd/DiffDelete/DiffChange is a good enough fix for me, however the functionality on your end has definitely changed recently, can't figure out how though, let me know if there's anything I can do to help with that though!

**Comment by airblade** [comment] 2019-02-06 07:45
@jam1garner The change is that previously the signs' foreground colours were hardcoded into vim-gitgutter, and the colours were those git-diff uses (in my terminal).  Now the signs' foreground colours are taken from the colourscheme's Diff* colours and not hardcoded into the plugin.

In other words, previously the signs' colours were based on git; now they are based on vim.

The reason for the change was to leave the colour decision up to the colourscheme.  I was happy with the original colours but I think this approach is more correct.

**Comment by mlittlej** [comment] 2019-02-06 12:24
+1 to @jam1garner's issue.

---

Responding to @airblade:

I have definitions for the GitGutterDiff* colors in my environment and I'm seeing the same issue.

![Imgur](https://i.imgur.com/gdtJYgc.png)

Another symptom that I'm seeing is that the bg color of the gutter is different from the rest of bgcolor that vim is using when it hasn't previously done so (vim should be using my theme bgcolor, not imposing it's own).

**Comment by airblade** [comment] 2019-02-06 12:45
@mlittlej The GitGutterDiff* definitions all look correct.  Evidently your signs aren't using them.

I suspect this is due to the order in which the colourscheme is loaded versus vim-gitgutter.  Do you load your colourscheme first?

Once your vim is open, does `:doautocmd ColorScheme` make any difference?

For the background colours, it looks like your `SignColumn` and `LineNr` highlight groups differ.  What does `:verbose highlight SignColumn` and `:verbose highlight LineNr` show?

**Comment by mlittlej** [comment] 2019-02-06 15:27
```
:verbose highlight LineNr
LineNr         xxx term=underline ctermfg=239 guifg=#4e4e4e guibg=#1c1c1c
        Last set from ~/dotfiles/vim/colors/muon.vim line 18
```
```
:verbose highlight SignColumn
SignColumn     xxx term=standout ctermfg=214 ctermbg=235 guifg=#ffaf00 guibg=#262626
                   links to LineNr
        Last set from ~/dotfiles/vim/bundle/vim-gitgutter/autoload/gitgutter/highlight.vim line 37
```

Using `:doautocmd ColorScheme` got rid of the color difference between the gutter and the line number column (so everything matched the LineNr bg color), but it didn't fix the foreground color issue with the git symbols.

**Comment by airblade** [comment] 2019-02-06 15:46
Is the Muon you are using online somewhere?  The one [here](https://github.com/gregsexton/Muon/blob/1bc55f8ba529215f5a53078fa6723428b71c9a6e/colors/muon.vim) defines LineNr on line 17, not line 18 as reported by your `:verbose highlight LineNr`.

Does `:gitgutter#highlight#define_sign_text_highlights()` after the `:doautocmd ColorScheme` make any difference?

**Comment by mlittlej** [comment] 2019-02-06 16:01
`:doautocmd ColorScheme gitgutter#highlight#define_sign_text_highlights()` not entirely sure if that's what you meant me to try, but that had no effect either - fgcolors are still blank.

My `muon.vim` suffers from me having edited over the course of years and years. But it's, broadly speaking, the same as the one you can find at: https://github.com/gregsexton/Muon/blob/master/colors/muon.vim

There's nothing in the diff of those two that's adding anything special, just a bunch of minor color tweaks for my own preference' sake.

**Comment by airblade** [comment] 2019-02-06 16:10
Sorry, no, I meant to write `:call gitgutter#highlight#define_sign_text_highlights()`.

**Comment by mlittlej** [comment] 2019-02-06 16:45
Nope, still no change to the fg colors.

**Comment by airblade** [comment] 2019-02-06 17:01
@mlittlej Is your vimrc online somewhere?

**Comment by mlittlej** [comment] 2019-02-06 17:11
https://gist.github.com/mlittlej/7bcf366bb5f423993b7698e9f3afa8ed

**Comment by jam1garner** [comment] 2019-02-06 19:13
> @mlittlej The GitGutterDiff* definitions all look correct. Evidently your signs aren't using them.
> 
> I suspect this is due to the order in which the colourscheme is loaded versus vim-gitgutter. Do you load your colourscheme first?
> 
> Once your vim is open, does `:doautocmd ColorScheme` make any difference?
> 
> For the background colours, it looks like your `SignColumn` and `LineNr` highlight groups differ. What does `:verbose highlight SignColumn` and `:verbose highlight LineNr` show?

Agreed, the current handling is better than beforehand and it's really not a big deal that this is a "breaking" change, although it sucks to deal with a bit. I have no real solution as this is a communication issue more than anythings, thanks!

**Comment by airblade** [comment] 2019-02-07 17:08
@mlittlej You could also try removing `syntax on` ([line 73](https://gist.github.com/mlittlej/7bcf366bb5f423993b7698e9f3afa8ed#file-my-vimrc-L73)) which seems redundant as you have already executed `syntax enable` in line 2.

**Comment by mlittlej** [comment] 2019-02-07 22:49
https://gist.github.com/mlittlej/0b89b1c38ee9a6646c904245749e6d57

Tried removing the `syntax on` line as well, to no effect.

I'm trying to remember when I noticed that this was a problem but I've been in "planning" mode as opposed to "development" mode recently, so I can't quite remember when I first noticed the issue. This year almost certainly though.

FWIW, here's the `ls -l` of my `bundles` folder:

```
drwxr-xr-x  6 mlittlej mlittlej 4096 Jan 16 10:52 colorizer
drwxr-xr-x  6 mlittlej mlittlej 4096 Oct 31 10:15 diffchar.vim
drwxr-xr-x  2 mlittlej mlittlej 4096 Feb  7  2018 gundo
drwxr-xr-x  8 mlittlej mlittlej 4096 Oct  6 16:37 gundo.vim
drwxr-xr-x 11 mlittlej mlittlej 4096 Oct  6 17:12 jedi-vim
drwxr-xr-x 10 mlittlej mlittlej 4096 Oct  6 16:43 nerdtree
drwxr-xr-x  8 mlittlej mlittlej 4096 Oct  6 16:26 syntastic
drwxr-xr-x  7 mlittlej mlittlej 4096 Oct  6 17:07 tabular
drwxr-xr-x  7 mlittlej mlittlej 4096 Oct  6 15:55 vim-airline
drwxr-xr-x  6 mlittlej mlittlej 4096 Oct  6 16:02 vim-airline-themes
drwxr-xr-x  8 mlittlej mlittlej 4096 Jan 11 17:48 vim-fugitive
drwxr-xr-x  8 mlittlej mlittlej 4096 Feb  6 12:15 vim-gitgutter
drwxr-xr-x  6 mlittlej mlittlej 4096 Nov  2 13:06 vim-python-pep8-indent
```

A quick look through my apt history suggests that `vim-common` got upgrade on Jan 8th as well, so something in there might be the cause?

`vim:amd64 (2:8.1.0549-1, 2:8.1.0693-2)`
```
$ sudo apt-cache policy vim
vim:
  Installed: 2:8.1.0693-2
  Candidate: 2:8.1.0875-1
  Version table:
     2:8.1.0875-1 500
        500 http://ftp.uk.debian.org/debian buster/main amd64 Packages
 *** 2:8.1.0693-2 100
        100 /var/lib/dpkg/status
     2:8.0.0197-4+deb9u1 500
        500 http://ftp.uk.debian.org/debian stretch/main amd64 Packages
```

Edit:

Upgrading to the slightly newer version of `vim` didn't help either...

**Comment by airblade** [comment] 2019-02-10 15:12
The `DiffAdd` in your colourscheme is:

```viml
hi DiffAdd		    ctermbg=22                              gui=None        guibg=#303030
```

It has no foreground colour defined.

In your screenshot above, `GitGutterAddDefault` has `ctermfg=2 guifg=#009900 guibg=#1c1c1c`.  Have you hard coded that somewhere?  If not, I don't know where `GitGutterAddDefault` got those colours from, given your colourscheme's `DiffAdd`.  It doesn't make sense.

**Comment by mlittlej** [comment] 2019-02-11 19:02
I'm honestly not sure what's going any more. I have a sneaking suspicion that the image above (the one with `ctermfg=2`) is from the older, pre-change version of gitgutter (where the values were getting pulled from the terminal git-diff colors, and all subsequent text is from post-change.

I'm just going to do a full re-install of my `.vim*` files (they're about due for an update/clean, you might've noticed) and work from a fresh install instead.

Cheers for the help.

**Comment by airblade** [comment] 2019-02-15 09:33
OK, I'll close this – please do open another issue if you still have any problems.

**Closed by airblade** 2019-02-15 09:33 UTC
